server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/sharing/server/exceptions.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
Currently Armeria is doing the request parsing work. When a request is invalid, such as invalid json (#27), or incorrect type (`maxResults` is not an int), it will throw an exception and report 500 Internal Error.
In this PR, we catch any unhandled exception when process a request, and convert it to `DeltaInternalException` when processing a request. Then we scope all exceptions that may contain sensitive information to a single type `DeltaInternalException`. Hence, `DeltaSharingServiceExceptionHandler` can safely expose the messages in the following exceptions to the user for better user experience and report 400 Bad Request:
- `scalapb.json4s.JsonFormatException`: Valid json string but invalid field type (#27).
- `com.fasterxml.jackson.databind.JsonMappingException`: Invalid json …
=> Improve error handling in Delta Sharing Server

python/delta_sharing/protocol.py, python/delta_sharing/tests/test_protocol.py
According to [PROTOCOL](https://github.com/delta-io/delta-sharing/blob/main/PROTOCOL.md)  definition, "stats" field of "File" is an optional field.
Therefore, "AddFile" and "from_json" method should accept JSON which have no "stats".
Signed-off-by: Masaru Dobashi <dobachi1983oss@gmail.com>
=> Fix AddFile to accept JSON which have no stats

python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_rest_client.py, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
Add two more tables and update existing integration tests accordingly:
- `share3.default.table4`: The table column order is not the same as parquet files.
- `share3.default.table5`: An empty table.
=> Add more test tables and update integration tests

python/requirements-dev.txt, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala
`DeltaSharingDataSource.setupFileSystem` needs to use `SparkContext`. Call it in `createRelation` so that `DeltaSharingDataSource` can be created without `SparkContext`.
=> Call DeltaSharingDataSource.setupFileSystem lazily

python/delta_sharing/converter.py, python/delta_sharing/reader.py, python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_reader.py, python/delta_sharing/tests/test_rest_client.py, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
This PR fixes two issues:
- When a table is empty, `load_as_pandas` should return an empty Pandas DataFrame with the table schema. Fixes #35 
- When the type of a data column is a complex type, `load_as_pandas` should not fail. In a Delta table, only partition columns are not allowed to use complex types.
=> Add columns to empty table in load_as_pandas and fix issues for complex types

python/delta_sharing/protocol.py, python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_protocol.py, python/delta_sharing/tests/test_rest_client.py, python/dev/lint-python
Removes slash in profile.endpoint when reading in the profile. If the slash is kept, we may have urls like `/delta-sharing//shares`
=> Remove extra slash in endpoint for Python connector

build.sbt
Add conf/ to server classpath so that users can put their hadoop configuration files in conf/ directly.
Manually checked the generated script and verified `conf/` is on the classpath.
=> Add conf/ to server classpath

python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_reader.py, python/delta_sharing/tests/test_rest_client.py, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
- Added a new table compressed with gzip to the test bucket.
- Added tests to make sure the client is able to read the table.
=> Test for non-default compression codec

python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_rest_client.py, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
When the items field of the protobuf is empty, the resulting json won't contain the items field. This PR adds checks so that we won't have KeyErrors or NullPointerExceptions if we have empty responses for listSchema and listTables.
Added tests with empty shares and schemas.
=> Fix KeyError in client when response contains empty items

dev/release.sh
Fix the incorrect commands in the release script. Found them when I was making 0.2.0 release. See https://github.com/delta-io/delta-sharing/releases/tag/v0.2.0 for the list of files the script is supposed to generate.
=> Fix server package steps in release script

build.sbt, server/src/main/scala/io/delta/sharing/server/CloudFileSigner.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala
Fixes #21 
This commit  adds support for sharing Delta tables on Azure Blob Storage and Data Lake Storage Gen2. In particular, this commit adds a new class `AzureFileSigner` which generates a pre-signed URL to Azure blob using a Shared Access Account Policy. Also, this commit automatically sets the Hadoop configuration with the `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY` environment variables, which is used to generate the pre-signed blob URLs.
Signed-off-by: Will Girten <will.girten@databricks.com>
=> Initial PR to add Support for Azure Data Lake Storage

.github/workflows/build-and-test.yml, README.md, build.sbt, python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_rest_client.py, python/dev/lint-python, server/src/main/scala/io/delta/sharing/server/CloudFileSigner.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/resources/core-site.xml, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
This is a followup PR for #56. There are multiple changes:
- Add integration tests for Azure.
- Change the pre-signed url generation for Azure to make sure it's scoped down to the path only. We also have tests verifying this.
- Refactor the code to leverage hadoop-azure to get credentials rather than from the system env. The user can just follow the hadoop-azure doc to set up the credentials. See the updated README for more information.
Closes #21
=> Fix Azure support for Delta Sharing Server

.github/workflows/build-and-test.yml, README.md, examples/python/quickstart_pandas.py, python/delta_sharing/delta_sharing.py, python/delta_sharing/reader.py, python/delta_sharing/tests/test_delta_sharing.py, python/setup.py
This PR adds a new parameter `limit` to `load_as_pandas`. Users can use this parameter to limit the number of rows to be loaded into a pandas DataFrame. It can be used to explore a shared table without loading the entire table into the memory.
This PR also upgrades pyarrow to 4.0.0 so that we can use [dataset.head](https://issues.apache.org/jira/browse/ARROW-9731) to load only the first N rows.
Closes #62
=> Add a limit parameter to 'load_as_pandas'

python/delta_sharing/delta_sharing.py, python/delta_sharing/tests/test_delta_sharing.py, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
Currently Python list_all_tables API doesn't work with servers using 0.2.0 and below. As per some user feedback, this PR makes it work with old versions by adding a fallback logic.
We don't need to update spark connector. Its DeltaSharingRestClient is private and built mainly for testing the server logic, so no users will be affected.
This PR adds a PR to test the fallback logic. I also manually verified `list_all_tables` using a local server running 0.2.0.
=> Add list_all_tables backward compatibility

dev/release.sh
- Set `GPG_TTY` so that it works for environments not set it.
- Use `--allow-empty` to commit the changes to update Python Connector version so that we can re-run this script even if the Python connector version has been updated.
=> Fix misc issues in the release script

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
Currently users can run `create table foo using deltaSharing` without location to create a Delta Sharing in Hive Metastore. However, such managed tables are useless because users won't be able to read the table. The default location of managed tables will be pointed to a file system path such as `/user/hive/warehouse/foo`, so the user will see an invalid path error. The path format of Delta Sharing must be `profile_file + "#<share-name>.<schema-name>.<table-name>"`.
This PR updates the code to block managed table creation, and adds a test for this. Also manually tested the following two cases to make sure we don't break external tables:
- Use an old version to create an **external** table and use the jar built by this PR to read it.
- Use the jar built by this PR to create an **external** …
=> Block managed table creation for Delta Sharing

PROTOCOL.md
Added edge case details with non-negative and 0 max results, and existence of page token.
Fixed JSON formatting.
Identified int types.
https://github.com/delta-io/delta-sharing/blob/c44815eb6b1984e59216e9b7e88b3eeb1b7631db/PROTOCOL.md
=> Enhance protocol documentation

.gitignore, build.sbt, server/src/main/scala/io/delta/sharing/server/CloudFileSigner.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
This is a PR for #20.
I implemented GCS support by using Google Cloud Client Library (https://cloud.google.com/storage/docs/reference/libraries) and Google Cloud Storage connector (https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage).
Google Cloud Storage connector (GCS connector) has a dependency problem with Apache Spark releated with Google Guava, so I added this library's shaded jar in server/lib (SBT Unmanaged dependencies, not Managed dependencies in build.sbt).
I implemented this very forcefully, is this no problem?
To use GCP for delta sharing server, you have to do 2 steps.
1. In your terminal, Do `export GOOGLE_APPLICATION_CREDENTIALS=</path/to/your_gcp_service_acount_key.json>`
2. In the server config (e,g, delta-sharing-server.yaml), add a setting for GCP …
=> Support GCS for delta sharing Server

python/delta_sharing/_yarl_patch.py, python/delta_sharing/reader.py, python/dev/pytest
This PR moves the hack for yarl into `_yarl_patch.py` and import it only if the urls are GCS pre-signed urls. This will avoid modifying yarl when using S3 or Azure.
=> Trigger the hack for yarl only if the urls are GCS pre-signed urls

.github/workflows/build-and-test.yml, python/setup.py
fsspec doesn't work with Python 3.6. It throws the following error when running in 3.6:
```
loop = <_UnixSelectorEventLoop running=True closed=False debug=False>
func = <bound method HTTPFileSystem.set_session of <fsspec.implementations.http.HTTPFileSystem object at 0x7f95c8e5b390>>
timeout = None, args = (), kwargs = ***
def sync(loop, func, *args, timeout=None, **kwargs):
"""
Make loop run coroutine until it returns. Runs in other thread
"""
timeout = timeout if timeout else None  # convert 0 or 0.0 to None
if loop is None or loop.is_closed():
raise RuntimeError("Loop is not running")
try:
>           loop0 = asyncio.events.get_running_loop()
E           AttributeError: module 'asyncio.events' has no attribute 'get_running_loop'
``` …
=> Remove python 3.6 support and test multiple python versions

python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_rest_client.py, server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala, server/src/main/scala/io/delta/sharing/server/model.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
Extends Delta Sharing Metadata with field: configuration. It's a string to string map, which contains table properties.
=> Extends Delta Sharing Metadata with field: configuration

PROTOCOL.md
Extends Delta Sharing PROTOCOL to support change data feed:
- Adds API: GET `{prefix}/shares/{share}/schemas/{schema}/tables/{table}/changes` 
- Extends API: POST `{prefix}/shares/{share}/schemas/{schema}/tables/{table}/query` with a new parameter `version`
- Extends Metadata with the `configuration` field, which is a map containing the configuration options of the table.
=> Extends Delta Sharing PROTOCOL to support change data feed

python/delta_sharing/protocol.py, python/delta_sharing/reader.py, python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_converter.py, python/delta_sharing/tests/test_protocol.py, python/delta_sharing/tests/test_reader.py, python/delta_sharing/tests/test_rest_client.py
This PR has the following changes:
1) Adds CDF actions (AddCdcFile, RemoveFile)
2) Convert CDF actions into pandas.
3) Unit tests.
It still does not have the rest client support for the query table changes RPC.
=> Add support for converting CDF actions in DeltaSharingReader.

python/delta_sharing/tests/test_rest_client.py, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharingCDCReader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
Respect TableConfig.startVersion in OSS delta sharing server:
- Adds field startVersion with default 0 in TableConfig
- respect startVersion for listFiles in DeltaSharingService
- respect startVersion for listCDFFiles in DeltaSharedTableLoader
- Re-structure functions of DeltaSharingCDCReader to validateCdfOptions and then queryCDF
=> Respect TableConfig.startVersion in OSS delta sharing server

server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala
This allows users to add requestTimeout override configuration to the `server-config.yaml` file in order to prevent armeria's default 30s timeout from killing responses.
https://javadoc.io/static/com.linecorp.armeria/armeria-javadoc/1.15.0/com/linecorp/armeria/server/ServerBuilder.html#requestTimeout(java.time.Duration)
Signed-off-by: Patrick McCauley <patrickjmccauley@gmail.com>
=> Add ability to configure armeria server request timeout

README.md
`s3://` paths usually are configured to use EMR's proprietary file system which we don't support. This PR asks users to use `s3a://` which should be configured to use Hadoop S3AFileSystem.
=> Document that tables should use s3a paths rather than s3 paths

server/src/main/scala/io/delta/sharing/server/CloudFileSigner.scala, server/src/test/scala/io/delta/sharing/server/CloudFileSignerSuite.scala
For a path such as `gs://delta_sharing_test/foo`, `getHost` will return null and trigger NPE. This PR changes the code to call GCS APIs to parse a path instead to avoid such issue (It calls `getAuthority` underlying instead).
This is not an issue for S3 or Azure because they do require the bucket name to be a valid host name (cannot contain `_`).
=> Fix GCS path parsing

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
RemoteDeltaCDFRelation incorrectly ignores the `requiredColumns` parameter. This PR fixes it and adds a test to verify the fix.
=> Fix a CDF bug when selecting some columns

python/delta_sharing/rest_client.py
Replace `logging.warn` (deprecated in [Python 2.7, 2011](https://github.com/python/cpython/commit/04d5bc00a219860c69ea17eaa633d3ab9917409f)) with `logging.warning` (added in [Python 2.3, 2003](https://github.com/python/cpython/commit/6fa635df7aa88ae9fd8b41ae42743341316c90f7)).
* https://docs.python.org/3/library/logging.html#logging.Logger.warning
* https://github.com/python/cpython/issues/57444
=> Replace deprecated logging.warn with logging.warning

python/delta_sharing/tests/test_rest_client.py, server/src/main/protobuf/protocol.proto, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharingCDCReader.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharingHistoryManager.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
Support timestamp in table query request in oss delta sharing server, only one of timestamp and version is supported, and they are only supported when cdfEnabled is true.
=> Support timestamp in table query request in oss delta sharing server

python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_rest_client.py, server/src/main/protobuf/protocol.proto, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/sharing/server/exceptions.scala, server/src/main/scala/io/delta/sharing/server/model.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharingCDCReader.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharingHistoryManager.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
Support startingVersion in queryTable rpc in OSS Delta Sharing Server, to query data change since startingVersion until the current version of the table.
Also, converted InvalidProtocolVersionException to be a client error instead of internal error in oss delta sharing server.
=> Support startingVersion in queryTable rpc in OSS Delta Sharing Server

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingProfileProvider.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
So that the spark connector can be forked and customized to send arbitrary HTTP headers to any specific implementation of Delta Sharing Server.
=> Add a Custom Http Header Provider

PROTOCOL.md, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
Return starting version instead of current table version in the header for time travel queries: 
- for queryTable with time travel parameters: version/timestamp/startingVersion
- for queryTableChanges
=> Return starting version instead of current table version in the header for time travel queries

python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_reader.py, python/delta_sharing/tests/test_rest_client.py, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
- Support startingTimestamp for getTableVersion
- Support GET http method for getTableVersion, and update DeltaSharingClient to use GET instead of HEAD
- Update both python and spark python client to issue GET instead of HEAD request for getTableVersion
- in python rest client, include table version in the response for list_files_in_table and query_table_metadata
- Check that queryTable with "timestamp" cannot exceeds TableConfig.startVersion
=> Support startingTimestamp and GET method for getTableVersion

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSourceOffset.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/main/scala/org/apache/spark/sql/DeltaSharingScanUtils.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingIntegrationTest.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
Adds DeltasharingSource, similar to DeltaSource, supports streaming addfiles, 
- local cache: sortedFetchedFiles
- 30 seconds interval is added for getTableVersion
- ignoreChanges/ignoreDeletes/maxFilesPerTrigger/maxBytesPerTrigger are supported
Not in this PR, will be supported in a separate PR
- readChangeFeed/readChangeData
- read compatibility check on schema
- SupportsTriggerAvailableNow
- startingTimestamp
=> Adds DeltasharingSource

python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_rest_client.py, server/src/main/scala/io/delta/sharing/server/model.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
Return metadata for each table version, if seen in delta log, on queryTable with startingVersion.
Also updated the share config for integration test, added share8, so that when adding new tables later, we don't need to update the test for share1.
=> Return metadata for each table version on queryTable with startingVersion 

project/plugins.sbt, python/delta_sharing/rest_client.py, server/src/main/protobuf/protocol.proto, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
This PR:
- adds a get table api 
- changes the route for retrieving the version to /share/{share}/schema/{schema}/table/{table}/version due to conflicts with the get table api
- upgrades dependencies for use on M1 macbook pro*
- test/testQuietly to integrationTest to fix tests expecting an integration test
(*) the current version of the scalapb library does not use a version of protoc that has publicly available arm64 builds and fails the local development
=> Add get table api

python/delta_sharing/tests/test_delta_sharing.py
Nit fix on the spark version used for python testing: from 1.0.0 to 0.6.0
=> Nit fix on the spark version used for python testing

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala
Refresh presigned urls for delta sharing streaming, non cdf queries
=> Refresh presigned urls for delta sharing streaming, non cdf queries

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingFileSystem.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingProfileProvider.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingFileSystemSuite.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala, spark/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala
Extends DeltaSharingProfileProvider to customize tablePath and refresher
=> Extends DeltaSharingProfileProvider to customize tablePath and refresher 

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, spark/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala
Refresh presigned urls for cdf queries in v0.5
=> Refresh presigned urls for cdf queries

PROTOCOL.md, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
In this change, delta sharing will try to get the table size from table metadata if it is available.
If not available, it will fall back to computing the size from full parquet scan.
The existing code always computes the size from parquet scan, making it a performance bottleneck.
Tested the following combinations:
New server, new connector -> avoids extra queryTable call
New server, old connector -> works (backwards compatibility)
Old server, new connector -> works (backwards compatibility)
=> Spark connector changes to consume size from metadata.

python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_rest_client.py, server/src/main/scala/io/delta/standalone/internal/DeltaSharingHistoryManager.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceCDFSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
Client side:
Support more flexible format for timestamp options in spark, to be similar with delta.
Server side:
Support ISO_OFFSET_DATE_TIME format for all timestamp related parameters: startingTimestamp, timestampAsOf, cdf.startingTimestamp, cdf.endingTimestamp.
=> Support more flexible format for timestamp options in spark 

PROTOCOL.md, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
In this change, delta sharing will try to get the table size from table metadata if it is available.
If not available, it will fall back to computing the size from full parquet scan.
The existing code always computes the size from parquet scan, making it a performance bottleneck.
Tested the following combinations:
New server, new connector -> avoids extra queryTable call
=> Spark connector changes to consume size from metadata in v0.5

PROTOCOL.md
PROTOCOL changes in release 0.6.0:
- Query Table Version: 
- change from HEAD to GET.
- with a `/version` suffix.
- Support parameter `startingTimestamp`.
- Read Data from a Table
- Support parameter `timestamp`.
- Support parameter `startingVersion`.
- The response can be data change files and include historical metadata for query with `startingVersion`. 
- Read Change Data Feed from a Table:
- Support parameter `includeHistoricalMetadata`
- The response will include historical metadata if `includeHistoricalMetadata` is set to true.
- Metadata now contains 3 optional fields: version/size/numFiles. version will be returned when querying table data with a version or timestamp parameter, or cdf query with includeHistoricalMetadata set to true, size/numFiles will be returned when available …
=> PROTOCOL changes in release 0.6.2

README.md, python/delta_sharing/tests/test_delta_sharing.py
Fix typo of start_version in load_table_changes_as_spark in README
=> Fix typo of start_version in load_table_changes_as_spark in README 

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
This PR plugs in json predicate tree generation from the spark provided SQL expression trees, and sends the json predicates to the server via delta sharing client.
I will send the protocol.md changes in a followup PR.
=> Plug in op conversion and generate json predicates.

server/src/main/protobuf/protocol.proto, server/src/main/scala/io/delta/sharing/server/SharedTableManager.scala, server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, server/src/test/scala/io/delta/sharing/server/SharedTableManagerSuite.scala, server/src/test/scala/io/delta/sharing/server/TestResource.scala, server/src/test/scala/io/delta/sharing/server/config/ServerConfigSuite.scala, server/src/universal/conf/delta-sharing-server.yaml.template
The protocol currently says the table ID is optional however in lots of client implementations it requires table IDs to be in place. This change returns table IDs on all the tables hosted by the reference server.
=> Add UUIDs as Table IDs on the reference server

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
This PR removes the base64 encoding for jsonPredicateHints from the spark client to preserver their readability.
=> remove base64 encoding from jsonPredicateHints.

PROTOCOL.md, server/src/main/scala/io/delta/sharing/server/SharedTableManager.scala
So that Table ID is unique as demanded by the PROTOCOL.md.
The `id` field in `TableConfig` is hard to set as optional because it does not work with the existing YAML->Scala reader.
=> Set optional Table ID to be None in API response when it is not available

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
This PR adds a flag to protect json predicate conversion.
=> add flag to protect json predicate conversion.

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala
Set spark.delta.sharing.jsonPredicateHints.enabled default to false
=> Set spark.delta.sharing.jsonPredicateHints.enabled default to false

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingFileSystem.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
This PR increases the default network timeout for the spark client.
This allows it to scale to larger tables that may require more time for metadata operations such as presigning urls.
=> Increase delta sharing network timeout.

README.md, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
We have added a `skipChangeCommits` flag for Structured Streaming with Delta source ([Here](https://github.com/delta-io/delta/pull/1616) is the PR for Delta). This PR aims to bring parity to Delta Sharing as a streaming source. Below is the description of `skipChangeCommits` flag and how it differs from existing `ignoreChanges` flag:
Added `skipChangeCommits` flag to entirely skip commits that contain `removeFiles` in Delta Sharing source for structured streaming. The purpose for this change is to replace the current `ignoreChanges` flag that could result in data duplication issues when using Delta Sharing as a structured streaming source with DELETE/UPDATE/MERGE INTO operations (e.g. GDPR)
Behavior for existing `ignoreChanges` flag:
- When there's `removeFile` detected in a commit, the …
=> Added skipChangeCommits support for Delta Sharing

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
In this PR, we optimize the way delta sharing client assembles the server response for pre-signed urls.
Instead of first concatenating and then splitting the response, we now avoid concatenation, making things more efficient.
It also avoid running into 1GB limit on string concatenation.
=> Optimize delta sharing spark client handling of presigned url response.

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, spark/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, spark/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala
Correct refreshing logic of pre-signed urls for delta sharing streaming:
1. refresh immediately if it already expired.
2. set the correct expiration time for a CachedTable 
Tested with a integration test from a notebook.
=> Correct refreshing logic of pre-signed urls for delta sharing streaming

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
Set spark.delta.sharing.source.refreshPresignedUrls.enabled default to true
=> Set spark.delta.sharing.source.refreshPresignedUrls.enabled default to true

PROTOCOL.md, README.md, server/src/main/protobuf/protocol.proto, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaCDFErrors.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceCDFSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
- Support endingVersion in queryTable RPC, this is to avoid fetching unneeded files from server upon refresh. 
- Support a new parameter: `maxVersionsPerRpc` for delta sharing streaming job.
=> Support endingVersion in queryTable RPC

PROTOCOL.md, server/src/main/scala/io/delta/sharing/server/CloudFileSigner.scala, server/src/main/scala/io/delta/sharing/server/model.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingProfileProvider.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala
- In delta sharing sever, add expirationTimestamp for each action in the response
- In delta sharing client, update refresh function to return the min expiration timestamp across all urls.
- In delta sharing client, refresh based on the expiration timestamp
- In DeltaSharingSource, updated the refresh function to refresh the `sortedFetchedFiles`, so it doesn't have to do an extra local refresh -- delegate the refresh to CachedTableManager entirely.
=> Add an optional `expirationTimestamp` field for pre signed urls

README.md, server/src/test/scala/io/delta/sharing/server/config/ServerConfigSuite.scala, server/src/universal/conf/delta-sharing-server.yaml.template
Add documentation for integrating Cloudflare R2. This implementation uses the R2 implementation of the S3 API and instructs on how to specify proper configurations to connect to R2. 
Closes #310
=> Add documentation for integrating R2

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingFileSystem.scala, spark/src/main/scala/io/delta/sharing/spark/RandomAccessHttpInputStream.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/io/delta/sharing/spark/util/ConfUtils.scala, spark/src/main/scala/io/delta/sharing/spark/util/RetryUtils.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala, spark/src/test/scala/io/delta/sharing/spark/util/ConfUtilsSuite.scala, spark/src/test/scala/io/delta/sharing/spark/util/RetryUtilsSuite.scala
In this PR, we are making the following changes:
- Add a maxRetryDurationLimit to the retry logic.
- Retry on socket timeout.
- Refactor/Consolidate spark configs
- Add unit tests.
=> Add maxRetryDuration in the retry logic in spark client; consolidate configs; add unit tests

python/delta_sharing/reader.py
The issue with the proxy env variables not being used when reading the data via the pre-signed urls when using the "load_as_pandas" which uses the fsspec and aiohttp libraries to read the data via the pre-signed urls.
this fix will make sure that the fsspec and aiohttp clients created will use the proxy settings if the proxy env variables are set in the environment.
=> Fix for issue #320

PROTOCOL.md, README.md, server/src/main/protobuf/protocol.proto, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaCDFErrors.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceCDFSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
This is a cherry-pick of https://github.com/delta-io/delta-sharing/pull/304 [commit](https://github.com/delta-io/delta-sharing/commit/8b211cfbbd322a40683e01f0d4f0720c4d0a976a) 
- Support endingVersion in queryTable RPC, this is to avoid fetching unneeded files from server upon refresh. 
- Support a new parameter: `maxVersionsPerRpc` for delta sharing streaming job.
- Added logInfo which is not in the original PR, I will add that in a separate PR.
=> Support endingVersion in queryTable RPC in delta-sharing 0.6

PROTOCOL.md
Update document about accepted timestamp format by the delta sharing server. Issue https://github.com/delta-io/delta-sharing/issues/336
=> Update document about accepted timestamp format by the delta sharing server

build.sbt, project/plugins.sbt
fixes the docker build part of #252 No issues using this docker container on my M2 mac.
If you want to verify the build result I did a ./build/sbt server/docker:publish to my own docker hub account results are here: https://hub.docker.com/repository/docker/krisgeus/delta-sharing-server/tags?page=1&ordering=last_updated
=> Implement multi arch docker build

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
1. Double check sortedFetchedFiles, to ensure we return the correct file set asked by the spark streaming engine.
2. set previousOffset even the returned DataFrame is empty.
=> [Branch-0.6] Double check sortedFetchedFiles and set previousOffset

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
1. Double check sortedFetchedFiles, to ensure we return the correct file set asked by the spark streaming engine.
2. Set previousOffset even the returned DataFrame is empty.
3. Added more logging.
same changes as https://github.com/delta-io/delta-sharing/pull/342 and https://github.com/delta-io/delta-sharing/pull/343
=> [main] Double check sortedFetchedFiles and set previousOffset

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, version.sbt
1. Double check sortedFetchedFiles, to ensure we return the correct file set asked by the spark streaming engine.
2. Set previousOffset even the returned DataFrame is empty.
3. Added more logging.
Tested with existing oss suites, and 2 notebook tests.
same changes as https://github.com/delta-io/delta-sharing/pull/342
=> [Branch-0.7] Double check sortedFetchedFiles and set previousOffset

client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/main/scala/io/delta/sharing/spark/filters/JsonPredicates.scala, spark/src/main/scala/io/delta/sharing/spark/filters/OpConverter.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/filters/JsonPredicateSuite.scala, spark/src/test/scala/io/delta/sharing/spark/filters/OpConverterSuite.scala
In the PR, we make the following changes.
1) Convert data Filters into json predicates.
2) Combine partiton and data Filters into combined json predicate op using an AND.
3) Add support for Float/Double types.
4) Unit tests.
The changes are off by default and behind a spark config.
=> Spark client changes for Json V2 predicates.

build.sbt, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceCDFSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
1. Use JsonRawValue in fasterxml.jackson instead of codehaus.jackson, to fix vulnerability check in DBR.
2. Fix streaming test failures with checkpoint caused by upgrade of new dependency.
=> Use JsonRawValue in fasterxml.jackson instead of codehaus.jackson

server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
- [Part 1](https://github.com/delta-io/delta-sharing/pull/352): Pagination for QueryTable at snapshot
- [Part 2](https://github.com/delta-io/delta-sharing/pull/353): Pagination for QueryTable from starting_version [[files changed](https://github.com/delta-io/delta-sharing/pull/353/files)]
- [Part 3](https://github.com/delta-io/delta-sharing/pull/354): Pagination for QueryTableChanges [[files changed](https://github.com/delta-io/delta-sharing/pull/354/files/ac7c8aaa6e011f9ca682e1d45b05c875eaa91834..ecd6bf410cc2d1ce5ded4091266ee899b2a8eb74)]
- [Part 4](https://github.com/delta-io/delta-sharing/pull/356): Client change [[files changed](https://github.com/delta-io/delta-sharing/pull/356/files/ecd6bf410cc2d1ce5ded4091266ee899b2a8eb74..f6d7d1e1b9b772034953440b6590c543f7d9927d)]
---
Support …
=> Pagination for QueryTable from starting_version

server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharingCDCReader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
- [Part 1](https://github.com/delta-io/delta-sharing/pull/352): Pagination for QueryTable at snapshot
- [Part 2](https://github.com/delta-io/delta-sharing/pull/353): Pagination for QueryTable from starting_version
- [Part 3](https://github.com/delta-io/delta-sharing/pull/354): Pagination for QueryTableChanges
- [Part 4](https://github.com/delta-io/delta-sharing/pull/356): Client change [[files changed](https://github.com/delta-io/delta-sharing/pull/356/files/c7271be600f1e8645d53a7c12d2578cceda4deee..b05024e06af268ecb7c2f9bd541071be3eb319ee)]
---
Support pagination for QueryTableChanges in reference server.
This is part 3 for issue https://github.com/delta-io/delta-sharing/issues/351.
=> Pagination for QueryTableChanges

python/delta_sharing/reader.py, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala
Fix two build errors: 
1. use a static Cast init function to allow delta-sharing-spark work for multiple spark versions. 
2. use isinstance for type comparison in python.
=> Fix two build errors: use a static Cast init function and isinstance for type comparison in python 

PROTOCOL.md
Many Delta Sharing connectors already do not send over the content-type header in the request. Existing Delta Sharing servers already accept requests without the header. This guidance will further ensure that existing connectors do not break and give more flexibility for the server.
Also fixed some formatting issues.
=> Protocol update: content-type request header in /query should be optional

server/src/main/scala/io/delta/sharing/server/model.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
- [Part 1](https://github.com/delta-io/delta-sharing/pull/352): Pagination for QueryTable at snapshot
- [Part 2](https://github.com/delta-io/delta-sharing/pull/353): Pagination for QueryTable from starting_version
- [Part 3](https://github.com/delta-io/delta-sharing/pull/354): Pagination for QueryTableChanges
- [Part 4](https://github.com/delta-io/delta-sharing/pull/362): Rename JSON object to endStreamAction and return minUrlExpirationTimestamp
- [Part 5](https://github.com/delta-io/delta-sharing/pull/356): Delta Sharing client changes
---
Introduce a new action type `EndStreamAction` in streaming response. This action should always be returned as the last line. For now, it includes two optional fields:
- nextPageToken: used to retrieve the subsequent page
- minUrlExpirationTimestamp: …
=> Introduce EndStreamAction and return minUrlExpirationTimestamp for paginated request

client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientDeltaSuite.scala
Few unit tests in DeltaSharingRestClientDeltaSuite are failing b/c we changed the file order returned from the DS server in https://github.com/delta-io/delta-sharing/pull/354.
This pr fixes the file orders in unit tests.
=> Fix tests in DeltaSharingRestClientDeltaSuite

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/model.scala, client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
- [Part 1](https://github.com/delta-io/delta-sharing/pull/352): Pagination for QueryTable at snapshot
- [Part 2](https://github.com/delta-io/delta-sharing/pull/353): Pagination for QueryTable from starting_version
- [Part 3](https://github.com/delta-io/delta-sharing/pull/354): Pagination for QueryTableChanges
- [Part 4](https://github.com/delta-io/delta-sharing/pull/362): Rename JSON object to endStreamAction and return minUrlExpirationTimestamp
- [Part 5](https://github.com/delta-io/delta-sharing/pull/356): Delta Sharing client changes
---
Change delta sharing client to send paginated request by looping internally to fetch all pages.
This is part 5 for issue https://github.com/delta-io/delta-sharing/issues/351
=> Query table pagination in Delta Sharing client

spark/src/main/scala/io/delta/sharing/spark/filters/JsonPredicates.scala, spark/src/main/scala/io/delta/sharing/spark/filters/OpConverter.scala, spark/src/test/scala/io/delta/sharing/spark/filters/OpConverterSuite.scala
In this PR, we add timestamp support in V2 predicates.
=> Add timestamp support in spark connector for V2 predicates.

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
Fix build errors: use a static Cast init function in all places under spark/, also cleaned up some unused imports.
=> Fix build errors: use a static Cast init function in all places under spark/

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/model.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientDeltaSuite.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
Use this [link](https://github.com/delta-io/delta-sharing/pull/386/files) to review incremental changes.
- [stack/refresh-token-server](https://github.com/delta-io/delta-sharing/pull/385)
- [stack/refresh-token-client](https://github.com/delta-io/delta-sharing/pull/386)
- [stack/refresh-token-spark](https://github.com/delta-io/delta-sharing/pull/387)
---
This pr adds refresh token support in delta sharing client:
- If the current query is for latest snapshot, set `includeRefreshToken=true` to retrieve the refresh token.
- Use `refreshToken` specified in `getFiles()` call for refresh query.
- Return refresh token to the caller as part of the `DeltaTableFiles` struct.
This is part 2 of https://github.com/delta-io/delta-sharing/issues/383.
=> Support refresh token in delta sharing client

client/src/main/scala/io/delta/sharing/client/DeltaSharingProfileProvider.scala, client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, client/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
Use this [link](https://github.com/delta-io/delta-sharing/pull/387/files) to review incremental changes.
- [stack/refresh-token-server](https://github.com/delta-io/delta-sharing/pull/385)
- [stack/refresh-token-client](https://github.com/delta-io/delta-sharing/pull/386)
- [stack/refresh-token-spark](https://github.com/delta-io/delta-sharing/pull/387)
---
This pr modifies `CachedTableManager` to support refresh token:
- Change `refresher` func to take `refreshToken: Option[String]`, and return `(idToUrlMap, minUrlExpiration, newRefreshToken)`
- The `refreshToken` will be stored in the `CachedTable`
- When refresh is needed for a cached table, call `cachedTable.refresher(cachedTable.refreshToken)` to update urls.
Note that the above change only applies to latest snapshot queries. For other …
=> CachedTableManager use refresh token to refresh urls

server/src/main/protobuf/protocol.proto, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala, server/src/main/scala/io/delta/sharing/server/model.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/universal/conf/delta-sharing-server.yaml.template, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingProfileProvider.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala, spark/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala
This pr adds refresh token fix to delta-sharing-spark branch-0.6:
- In `DeltaSharingClient`, if the query is for latest snapshot, set `includeRefreshToken=true` to retrieve the refresh token.
- In `CachedTableManager`, when refreshing a cached table, use `refreshToken` to update urls.
- Added tests for client side changes, also added refresh token changes in the reference server to support integration test.
=> Refresh token branch-0.6 fix

server/src/main/protobuf/protocol.proto, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala, server/src/main/scala/io/delta/sharing/server/model.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/universal/conf/delta-sharing-server.yaml.template, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingProfileProvider.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala, spark/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala
This pr adds refresh token fix to delta-sharing-spark branch-0.7:
- In `DeltaSharingClient`, if the query is for latest snapshot, set `includeRefreshToken=true` to retrieve the refresh token.
- In `CachedTableManager`, when refreshing a cached table, use `refreshToken` to update urls.
- Added tests for client side changes, also added refresh token changes in the reference server to support integration test.
=> Refresh token branch-0.7 fix

python/delta_sharing/reader.py, python/delta_sharing/tests/test_reader.py
There's a bug where calling `to_pandas` on a partitioned table with differing Delta and parquet metadata, the resulting pandas dataframe would result in the columns being None. Specifically the difference in the metadata is the casing in the column names. 
ex: 
Delta columns: ["MARKET", "DATA", "branch"]
Parquet columns: ["market", "data", "branch"]
This PR fixes that issue by performing a case-insensitive lookup of the columns.
=> Fix bug where to_pandas doesn't properly handle the case when column names between Delta and parquet metadata are different in casing

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
1. Throw error when respondedFormat != requested responseFormat. This is to alert when an advanced client is querying an old server, to let the client query the files with parquet format sharing.
2. fix the parsing of delta-sharing-capabilities header in server.
Tests:
1. As in integration test we are using the oss server which always return the correct responseFormat, I tested this change by manually disable the responseFormat in server and verified the error below:
```
[info] - getMetadata with configuration *** FAILED ***
[info]   java.lang.IllegalArgumentException: The responseFormat returned from the delta sharing server doesn't match the requested responseFormat: respondedFormat(parquet) != requestedFormat(delta).This is likely because the server is not upgraded to support delta …
```
=> Throw error when respondedFormat doesn't match requested responseFormat

client/src/main/scala/io/delta/sharing/filters/JsonPredicates.scala, client/src/main/scala/io/delta/sharing/filters/OpConverter.scala, client/src/test/scala/io/delta/sharing/client/util/RetryUtilsSuite.scala, client/src/test/scala/io/delta/sharing/filters/JsonPredicateSuite.scala, client/src/test/scala/io/delta/sharing/filters/OpConverterSuite.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
Move JsonPredicates and OpConverter and RetryUtilsSuite from spark to client, as they are of delta sharing core logic.
=> Move JsonPredicates, OpConverter and RetryUtilsSuite from spark to client

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/RandomAccessHttpInputStream.scala, client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala, version.sbt
Improve error message when seeing unrecognized file from server: output the line instead of file.
And add two configs:
- "spark.delta.sharing.streaming.queryTableVersionIntervalSeconds", cannot be less than 30 seconds
- "spark.delta.sharing.ignoreUnparsedActions"
=> Improve error message on unrecognized file from server, and add two configs

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/RandomAccessHttpInputStream.scala, client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
Improve error message when seeing unrecognized file from server: output the line instead of file.
And add two configs:
- "spark.delta.sharing.streaming.queryTableVersionIntervalSeconds", cannot be less than 30 seconds
- "spark.delta.sharing.ignoreUnparsedActions"
=> Improve error message on unrecognized file from server, and add two configs, in 1.0

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RandomAccessHttpInputStream.scala, spark/src/main/scala/io/delta/sharing/spark/util/ConfUtils.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
Improve error message when seeing unrecognized file from server: output the line instead of file.
And add two configs:
- "spark.delta.sharing.streaming.queryTableVersionIntervalSeconds", cannot be less than 30 seconds
- "spark.delta.sharing.ignoreUnparsedActions"
=> Improve error message on unrecognized file from server, and add two configs in 0.7

python/delta_sharing/reader.py, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RandomAccessHttpInputStream.scala, spark/src/main/scala/io/delta/sharing/spark/util/ConfUtils.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
Improve error message when seeing unrecognized file from server: output the line instead of file.
And add two configs:
- "spark.delta.sharing.streaming.queryTableVersionIntervalSeconds", cannot be less than 30 seconds
- "spark.delta.sharing.ignoreUnparsedActions"
=> Improve error message on unrecognized file from server, and add two configs in 0.6

server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/main/scala/io/delta/standalone/internal/model.scala
Fix the test failures in: https://github.com/delta-io/delta-sharing/actions/runs/6255145774/job/17116036562, as this is reference server purely for demonstration purpose, this should be ok.
The reason is the unexpected serialization of fields of Metadata in the json string, which in theory should not appear. 
schema/dataSchema/partitionSchema which should be ignored: https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala#L195
```
{"metaData":{"deltaMetadata":{"id":"ed96aa41-1d81-4b7f-8fb5-846878b4b0cf","format":{"provider":"parquet","options":{}},"schemaString":"{\"type\":\"struct\",\"fields\":[{\"name\":\"eventTime\",\"type\":\"timestamp\",\"nullable\":true,\"metadata\":{}},{\"name\":\"date\",\"type\":\"date\",\"null …
```
=> Fix Tests with a copy of DeltaMetadata

server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/main/scala/io/delta/standalone/internal/model.scala
The same change as https://github.com/delta-io/delta-sharing/pull/407
Fix the test failures in: https://github.com/delta-io/delta-sharing/actions/runs/6255145774/job/17116036562, as this is reference server purely for demonstration purpose, this should be ok.
The reason is the unexpected serialization of fields of Metadata in the json string, which in theory should not appear. 
schema/dataSchema/partitionSchema which should be ignored: https://github.com/delta-io/connectors/blob/master/standalone/src/main/scala/io/delta/standalone/internal/actions/actions.scala#L195
```
{"metaData":{"deltaMetadata":{"id":"ed96aa41-1d81-4b7f-8fb5-846878b4b0cf","format":{"provider":"parquet","options":{}},"schemaString":"{\"type\":\"struct\",\"fields\":[{\"name\":\"eventTime\",\"type\":\"timestamp\",\"nullab …
```
=> Fix Tests with a copy of DeltaMetadata in branch-1.0

PROTOCOL.md
Add Streaming Specs in PROTOCOL in branch 0.7: `maxVersionPerRpc` and `spark.delta.sharing.streaming.queryTableVersionIntervalSeconds`
=> Add Streaming Specs in PROTOCOL in branch 0.7

PROTOCOL.md
Add Streaming Specs in PROTOCOL in branch 0.6: `maxVersionPerRpc` and `spark.delta.sharing.streaming.queryTableVersionIntervalSeconds`
=> Add Streaming Specs in PROTOCOL in branch 0.6

client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
RemoteDeltaLog can be initialized with `initDeltaTableMetadata`.
=> RemoteDeltaLog accept input Metadata

client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
RemoteDeltaLog can be initialized with `initDeltaTableMetadata`, same change as https://github.com/delta-io/delta-sharing/pull/421
=> RemoteDeltaLog accept input Metadata in branch 1.0

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/model.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
Allow different response format, will let the caller decide the behavior, same change as in https://github.com/delta-io/delta-sharing/pull/420
=> Allow different response format in branch-1.0

PROTOCOL.md
The same changes as https://github.com/delta-io/delta-sharing/pull/413 in branch 1.0.
Update delta sharing protocol:
- delta-sharing-capabilities header
- delta format 
- streaming specs: `maxVersionPerRpc` and `spark.delta.sharing.streaming.queryTableVersionIntervalSeconds`
=> Update delta sharing protocol in branch-1.0

PROTOCOL.md, client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, client/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala
Allow list of responseFormat in the request http header, separated by comma(`responseFormat=parquet,delta`), but require only one decided responseformat in the response.
And throw error if the respondedFormat is not in the list of the request.
=> Allow list of resopnseFormat

PROTOCOL.md, client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, client/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala
The same change as in https://github.com/delta-io/delta-sharing/pull/426
Allow list of responseFormat in the request http header, separated by comma(`responseFormat=parquet,delta`), but require only one decided responseformat in the response.
And throw error if the respondedFormat is not in the list of the request.
=> Allow list of resopnseFormat in branch-1.0

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
- Throw error when latest table version from the server is smaller than previous version.
- Add logging on number of files fetched from the server.
=> Improve error handling and logging in DeltaSharingSource in branch 0.6

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
- Throw error when latest table version from the server is smaller than previous version.
- Add logging on number of files fetched from the server.
=> Improve error handling and logging in DeltaSharingSource in branch 0.7

client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
- Throw error when latest table version from the server is smaller than previous version.
- Add logging on number of files fetched from the server.
=> Improve error handling and logging in DeltaSharingSource in branch 1.0

client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
- Throw error when latest table version from the server is smaller than previous version.
- Add logging on number of files fetched from the server.
=> Improve error handling and logging in DeltaSharingSource

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
Introduce Timestamp and UUID as suffix to table path in RemoteDeltaLog, to avoid two queries on the same table override the CachedTableManager entry for each other.
=> [DTS-2474] Introduce Timestamp and UUID as suffix to table path in RemoteDeltaLog

client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
Introduce Timestamp and UUID as suffix to table path in RemoteDeltaLog, to avoid two queries on the same table override the CachedTableManager entry for each other.
=> [DTS-2474] Introduce Timestamp and UUID as suffix to table path in RemoteDeltaLog in branch 1.0

client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
Introduce Timestamp and UUID as suffix to table path in RemoteDeltaLog, to avoid two queries on the same table override the CachedTableManager entry for each other.
=> [DTS-2474] Introduce Timestamp and UUID as suffix to table path in RemoteDeltaLog in main

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
Add per page logging for paginated requests.
=> Add more logging for paginated query requests

client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystem.scala, client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemSuite.scala, client/src/test/scala/io/delta/sharing/client/util/ConfUtilsSuite.scala, client/src/test/scala/io/delta/sharing/client/util/ProxyServer.scala
Adds support for Http Proxy when reading data from storage
sample configuration:
```
spark.delta.sharing.network.proxyHost=1.2.3.4
spark.delta.sharing.network.proxyPort=3128
spark.delta.sharing.network.noProxyHosts=5.6.7.8,12.13.14.15
```
=> Add support for http proxy

client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystem.scala, client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemSuite.scala, client/src/test/scala/io/delta/sharing/client/util/ConfUtilsSuite.scala, client/src/test/scala/io/delta/sharing/client/util/ProxyServer.scala
Adds support for Http Proxy when reading data from storage
sample configuration:
```
spark.delta.sharing.network.proxyHost=1.2.3.4
spark.delta.sharing.network.proxyPort=3128
spark.delta.sharing.network.noProxyHosts=5.6.7.8,12.13.14.15
```
=> Add support for http proxy (#450)

python/delta_sharing/delta_sharing.py, python/delta_sharing/tests/test_delta_sharing.py
In this PR, we add support for json predicate hints in load_as_pandas method.
The functionality is tested by unit tests.
=> Add json predicate hints to load_as_pandas.

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingFileSystem.scala
Adds more logging in DeltaSharingFileSystem, to understand # of calls on pre-signed urls.
Same PR in branch-0.7 as https://github.com/delta-io/delta-sharing/pull/456
=> Adds more logging in DeltaSharingFileSystem in branch 0.7

spark/src/main/scala/io/delta/sharing/spark/util/RetryUtils.scala
Do not retry on ConnectionClosedException, because it can be caused by invalid json returned from the delta sharing server.
The same PR as https://github.com/delta-io/delta-sharing/pull/467
=> Do not retry on ConnectionClosedException in branch 0.7

client/src/main/scala/io/delta/sharing/client/util/RetryUtils.scala
Do not retry on ConnectionClosedException, because it can be caused by invalid json returned from the delta sharing server.
The same PR as https://github.com/delta-io/delta-sharing/pull/467
=> Do not retry on ConnectionClosedException in branch-1.0

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
Handle ConnectionClosedException in place in DeltaSharingRestClient.getResponse, so we can surface the invalid json string of the error to the user.
=> Handle ConnectionClosedException in place in DeltaSharingRestClient.getResponse

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
Handle ConnectionClosedException in place in DeltaSharingRestClient.getResponse in branch 1.0, so we can surface the invalid json string of the error to the user.
=> Handle ConnectionClosedException in place in branch-1.0

client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
Lower the streaming rpc interval to 10s, default is still 30s
=> [Streaming] Lower the minimum streaming rpc interval to 10s

client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
Lower the rpc interval to 10s
The same change as in #477
=> [Streaming] Lower the minimum streaming rpc interval to 10s  in branch 1.0

python/delta_sharing/delta_sharing.py, python/delta_sharing/tests/test_delta_sharing.py
In this PR, we add support for json predicate hints in load_as_pandas method.
The functionality is tested by unit tests. The same change as in #454
=> Add json predicate hints to load_as_pandas in branch 1.0

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
Add queryID in userAgent for spark delta sharing queries in branch 0.7.
And add log for getTableVersion in DeltaSharingSource.
=> Add queryID in userAgent for spark delta sharing queries in branch 0.7

server/src/main/scala/io/delta/sharing/server/DeltaSharedTableLoader.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTable.scala
Part of effort for supporting Delta Sharing Python to Read Shared DV/CM tables. Refactoring code so that a new DeltaSharedTableKernel can be created and the loader does not care about the DeltaSharedTableImplementation. 
In this refactor I brought the DeltaSharedTableLoader to its own file in the server package. I renamed the old file to DeltaSharedTable
=> Code refactor to split logic for DeltaSharedTableLoader and DeltaSharedTable

server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala, server/src/universal/conf/delta-sharing-server.yaml.template
Enable evaluateJsonPredicateHintsV2 in server, 
this could fix DeltaSharingSuite:cdf_table_with_partition: filter success, caused by jsonPredicateHintV2 evaluation in the server
=> Enable evaluateJsonPredicateHintsV2 in server

build.sbt, client/src/main/scala/io/delta/sharing/client/RandomAccessHttpInputStream.scala, server/src/main/scala/io/delta/sharing/server/CloudFileSigner.scala
upgrading hadoop version so it is compatible with delta-kernel
=> DTS-3385: upgrade hadoop version

build.sbt, client/src/main/scala/io/delta/sharing/client/RandomAccessHttpInputStream.scala, client/src/test/scala/io/delta/sharing/client/RandomAccessHttpInputStreamSuite.scala
When the client accesses the URI of a file in a shared table, it no longer logs the URI. This addresses the security concerns of logging presigned URLs.
=> DTS-3397: do not log URLs on access errors

client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, server/src/main/scala/io/delta/kernelsharedtable/DeltaSharedTableKernel.scala, server/src/main/scala/io/delta/sharing/server/DeltaAction.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharedTableProtocol.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/sharing/server/model.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTable.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
getMetadata now uses delta-kernel
=> DTS-3385: Switch getMetadata to use delta-kernel

python/delta_sharing/tests/test_delta_sharing.py, server/src/main/scala/io/delta/kernelsharedtable/DeltaSharedTableKernel.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/sharing/server/util/JsonUtils.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
limit hints for query supported by delta-kernel
=> limit hints for query supported by delta-kernel

python/delta_sharing/reader.py, python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_reader.py, python/delta_sharing/tests/test_rest_client.py
Added functions to set delta format headers. Added function to autoresolve query format. Added tests to verify correct format is being returned for different tables
=> Autoresolve query format and support delta format RPC call

python/delta_sharing/rest_client.py
Super minor refactor to move delta-table-version string as a constant throughout the rest_client.py file to be consistent with the style for the DELTA_SHARING_CAPABILITIES_HEADER
=> Refactor Header

python/delta_sharing/reader.py, python/delta_sharing/tests/test_delta_sharing.py
Support query of tables with no data (includes LIMIT 0 queries)
=> Support Empty Table Sharing with Kernel

python/delta-kernel-rust-sharing-wrapper/Cargo.toml
add openssl as dependencies in Cargo, so that it can support cross release on linux arm64
=> add openssl as dependencies in Cargo

README.md, python/delta-kernel-rust-sharing-wrapper/README.md
add README for delta-kernel-rust-sharing-wrapper, for examples on how to build the wrapper locally.
=> add README for delta-kernel-rust-sharing-wrapper

python/delta-kernel-rust-sharing-wrapper/Cargo.toml, python/delta_sharing/version.py, python/setup.py
Add delta-kernel-rust-sharing-wrapper as a install requirement for delta_sharing
=> Add delta-kernel-rust-sharing-wrapper as a install requirement for delta_sharing

python/setup.py
Require delta-kernel-rust-sharing-wrapper for delta_sharing installation
=> Require delta-kernel-rust-sharing-wrapper for delta_sharing installation

python/delta_sharing/_internal_auth.py, python/delta_sharing/auth.py, python/delta_sharing/protocol.py, python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_auth.py, python/delta_sharing/tests/test_oauth_client.py, python/delta_sharing/tests/test_profile_oauth2.json, python/delta_sharing/tests/test_protocol.py
The current OAuth implementation in the Python client does not reuse access tokens. Instead, it exchanges the client-id and client-secret for a new access token with every request. This behavior increases the load on the tokenEndpoint and introduces unnecessary latency in the request processing.
This PR updates the OAuth implementation to oauth reuse access tokens, aligning the Python client with the OAuth behavior of the Scala client, as detailed in this [PR for the Scala client](https://github.com/delta-io/delta-sharing/pull/553).
For additional context on the usage of auth_provider and its functionality, please refer to the description in the original PR for the Spark client.
=> Python OAuth client_credentials support

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
Log additional queryId and table id and table name
=> Log additional queryId and table id and table name 

client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, client/src/main/scala/org/apache/spark/sql/DeltaSharingScanUtils.scala
Currently delta-sharing-client is not compatible with Spark Master due to this commit
https://github.com/apache/spark/commit/a767f5cb1704075ee249169e8faf2ab3610b9dbc#diff-81eca9f7af2e9b23b13904131c3d32b0af9e9e1dcc7ddb5efba13201b00066c4 which changes the Column constructor. This PR changes `new Column(...)` to `Column(...)` to use the constructors in `object Column`, so delta-sharing-client can cross compile with both spark-3.5 and spark-4.0. 
Tested locally in sbt shell:
- **Compile with spark-3.x:** run `client/compile` without changing `build.sbt` > finished successfully
- **Compile with spark-4.0:** set `sparkVersion = "4.0.0-preview1"` in `build.sbt` > run `reload` > run `++ 2.13.11` to switch to scala 2.13 (spark-4.0 only runs on scala 2.13) > run `client/compile` > finished …
=> Make delta-sharing-client compatible with Spark 4.0

client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, client/src/main/scala/org/apache/spark/sql/DeltaSharingScanUtils.scala
Backport https://github.com/delta-io/delta-sharing/pull/582 to branch-1.2
=> [1.2] Make delta-sharing-client compatible with Spark 4.0

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
Add additional logging in DeltaSharingClient and DeltaSharingSource:
- ids and names for every log: queryId, tableId, and tableName.
- number of files returned in a query.
- errors detected in delta sharing client.
- For each DeltaSharingSource, add a sourceId.
=> Add additional logging in DeltaSharingClient and DeltaSharingSource

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala, version.sbt
Add additional logging in DeltaSharingClient and DeltaSharingSource in branch-1.1:
- ids and names for every log: queryId, tableId, and tableName.
- number of files returned in a query.
- errors detected in delta sharing client.
- For each DeltaSharingSource, add a sourceId.
=> Add additional logging in DeltaSharingClient and DeltaSharingSource Branch 1.1

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
Rename header from endStreamAction to includeEndStreamAction:
This name suggests that the header is a directive or option that indicates the inclusion of the EndStreamAction. It clearly communicates its purpose and indicates that it may affect both the request and response.
=> Rename header from endStreamAction to includeEndStreamAction

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/main/scala/io/delta/sharing/client/util/RetryUtils.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientDeltaSuite.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, client/src/test/scala/io/delta/sharing/client/util/ConfUtilsSuite.scala, client/src/test/scala/io/delta/sharing/client/util/RetryUtilsSuite.scala, server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
Backport includeEndStreamAction in DeltasharingService to branch-1.1
=> Backport includeEndStreamAction in DeltasharingService to branch-1.1

server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala, server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala, server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/main/scala/io/delta/sharing/spark/util/ConfUtils.scala, spark/src/main/scala/io/delta/sharing/spark/util/RetryUtils.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala, spark/src/test/scala/io/delta/sharing/spark/util/ConfUtilsSuite.scala, spark/src/test/scala/io/delta/sharing/spark/util/RetryUtilsSuite.scala
Backport includeEndStreamAction in DeltasharingService to branch-0.7
=> Backport includeEndStreamAction in DeltasharingService to branch-0.7

client/src/main/scala/io/delta/sharing/spark/perf/DeltaSharingLimitPushDown.scala
This PR introduces a shim to address the new parameter in LogicalRelation in Spark 4.0.
Since Delta Sharing does not perform cross compilation for Spark version and Spark 4.0 is expected to be released in early next year, this PR would help to defer the effort of cross compilation with multiple artifacts till really needed.
=> Use reflection to address the new parameter in LogicalRelation in Spark 4.0

client/src/main/scala/io/delta/sharing/spark/perf/DeltaSharingLimitPushDown.scala
> #603 
DeltaSharingLimitPushDown uses the pattern with LogicalRelation which could change, in terms of parameter in constructor. Spark community made a change in upcoming Spark 4.0 (https://github.com/apache/spark/pull/48676) to add a new parameter in LogicalRelation, and the change will break the pattern.
Since the pattern only picks up the relation from LogicalRelation, the pattern object Spark community introduced along with the above change (https://github.com/apache/spark/pull/48605) would be helpful to not encounter the issue in upcoming Spark 4.0 when Delta Sharing supports the version.
> #604 
This PR introduces a shim to address the new parameter in LogicalRelation in Spark 4.0.
Since Delta Sharing does not perform cross compilation for Spark version and Spark 4.0 is expected to …
=> Sync back the change of #603 and #604 to branch-1.2 to make 1.2 work with Spark 4.0

python/delta-kernel-rust-sharing-wrapper/Cargo.toml, python/delta-kernel-rust-sharing-wrapper/src/lib.rs
Existing python tests should be sufficient for correctness. Is any performance testing necessary?
=> Upgrade delta-kernel-rs to 0.5

.github/workflows/build-kernel-wheels.yml, python/delta-kernel-rust-sharing-wrapper/.gitignore, python/delta-kernel-rust-sharing-wrapper/Cargo.toml, python/delta-kernel-rust-sharing-wrapper/src/lib.rs
To be released as delta-kernel-rust-sharing-wrapper 0.2.0
=> Rust bindings for CDF reads

README.md, python/setup.py
Update references to the rust wrapper to use version 0.2.0
=> reference rust wrapper 0.2.0

.github/workflows/build-kernel-wheels.yml
Previously, the ARM jobs for Linux and Windows were non-functional and created the same wheel as their x86 counterpart. When the final merge job runs, the existence of two identical wheel files caused the wheel in the merged zip file to potentially get corrupted. This PR fixes that issue by removing the ARM jobs for Linux and Windows.
To verify that the wheels are fixed, I re-ran the merge action 10 times, and none of the wheels in any of the runs were corrupted. In contrast, 6 out of 10 runs with the previous build workflow had at least one wheel that was corrupted. Corruption was determined by checking if the wheel files would unzip, since a wheel file is a ZIP archive under the hood.
=> Fix wheels build by removing duplicate wheels

.github/workflows/build-kernel-wheels.yml, python/delta-kernel-rust-sharing-wrapper/Cargo.toml
Bump version to 0.2.1 for releasing the fixed build.
The path for the workflows also was not updated after renaming python/delta-sharing-kernel to python/delta-kernel-rust-sharing-wrapper. I believe it was updated while working on #612 but accidentally got undone before it was merged.
=> update delta-kernel-rust-sharing-wrapper to 0.2.1 and fix path in workflows

.github/workflows/build-kernel-wheels.yml, README.md, python/delta-kernel-rust-sharing-wrapper/Cargo.toml
Merged in fixes from main.
Don't need to update the rust wrapper's version in the dependencies as we had >=0.2.0. Since rust wrapper 0.2.0 was yanked, 0.2.1 will be used when installing delta-sharing 1.3.1.
=> Merge fixes from main to 1.3 branch

python/delta_sharing/_internal_auth.py, python/delta_sharing/tests/test_oauth_client.py
**TL;DR:** This PR enhances the OAuth client to support cases where the expires_in field in the token response is returned as a string instead of an integer. While the OAuth 2.0 specification mandates that expires_in should be an integer  [RFC 6749 Section 4.1.4](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.4), some OAuth servers return it as a string, leading to potential compatibility issues.
Certain OAuth implementations deviate from the standard and return expires_in as a string, e.g.:
```
{
"access_token": "example-token",
"expires_in": "3600",  // Returned as a string
"token_type": "Bearer"
}
```
This causes failures when the client expects the field to always be an integer.
Solution
This PR updates the token parsing logic to:
1.	Check the type of the expires_in field. …
=> Improvement python delta-sharing client: convert expires_in as string to int, if returned as string

python/delta_sharing/_internal_auth.py, python/delta_sharing/tests/test_oauth_client.py
This PR cherry picks https://github.com/delta-io/delta-sharing/pull/628 to python-branch-1.3
**TL;DR:** This PR enhances the OAuth client to support cases where the expires_in field in the token response is returned as a string instead of an integer. While the OAuth 2.0 specification mandates that expires_in should be an integer  [RFC 6749 Section 4.1.4](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.4), some OAuth servers return it as a string, leading to potential compatibility issues.
Certain OAuth implementations deviate from the standard and return expires_in as a string, e.g.:
```
{
"access_token": "example-token",
"expires_in": "3600",  // Returned as a string
"token_type": "Bearer"
}
```
This causes failures when the client expects the field to always be an integer. …
=> cherry pick PR #628 to python-branch-1.3

client/src/main/scala/io/delta/sharing/client/auth/OAuthClient.scala, client/src/test/scala/io/delta/sharing/client/auth/OAuthClientSuite.scala
TL;DR This PR improves oauth-client in spark-client to support parsing expires_in as string similar to the changes for the python client: https://github.com/delta-io/delta-sharing/pull/628
Detail:
This PR enhances the OAuth client to support cases where the expires_in field in the token response is returned as a string instead of an integer. While the OAuth 2.0 specification mandates that expires_in should be an integer [RFC 6749 Section 4.1.4](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.4), some OAuth servers return it as a string, leading to potential compatibility issues.
Certain OAuth implementations deviate from the standard and return expires_in as a string, e.g.:
```
{
"access_token": "example-token",
"expires_in": "3600",  // Returned as a string
"token_type": …
```
=> Improvement spark delta-sharing client: convert expires_in as string to int, if returned as string 

python/delta-kernel-rust-sharing-wrapper/Cargo.toml
This version fixes a bug where reading a table partitioned on timestamp may error.
=> Upgrade delta-kernel-rs to 0.6.1

client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
This PR improves the strict schema string match with smarter matching i.e. subset matching
Added unit test
Tested against DBR:
=> Improve strict schema string match with smarter matching

README.md, python/README.md, python/delta-kernel-rust-sharing-wrapper/Cargo.toml
Running `maturin build --sdist` creates a source tarball. Uploading the source tarball to PyPI would allow for delta-kernel-rust-sharing-wrapper to be installed from pip even on platforms that do not explicitly have a wheel built for them. This PR updates the README accordingly.
=> Include source in maturin build of delta-kernel-rust-sharing-wrapper

client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
* Improve strict schema string match with smarter matching
* Add Spark conf to gate the structural schema matching
=> Backport Improve strict schema string match with smarter matching (#621) to branch-1.2

client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
* Improve strict schema string match with smarter matching
* Add Spark conf to gate the structural schema matching
=> Cherrypick Improve strict schema string match with smarter matching into version 1.1

.github/workflows/build-and-test.yml
@actions/cache v2 has been deprecated. No changes are needed as this upgrade is fully backwards compatible. See https://github.com/actions/toolkit/blob/main/packages/cache/README.md.
=> Upgrade actions/cache to v4

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala
Add more logging for client and cache for better debug ability.
=> Add more logging for client and cache

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/main/scala/io/delta/sharing/client/util/RetryUtils.scala, client/src/test/scala/io/delta/sharing/client/util/RetryUtilsSuite.scala
This PR introduces the following changes to the retry logic:
1. Reduced Retry Attempts: The number of retries is reduced from 10 to 3. If the Delta Sharing server returns an error, the client will either retry 3 times or retry for a maximum of 10 minutes, whichever occurs first. This adjustment allows the recipient to fail faster.
2. Introduced retry sleep interval: A sleep interval between retries has been introduced, with a default duration of 1000 milliseconds. The sleep time would double after each retry.
=> [DTS-4838] Optimize Retry Logic: Reduce Attempts and Adaptive Sleep Intervals

python/delta_sharing/reader.py, python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_reader.py, server/src/test/scala/io/delta/sharing/server/TestResource.scala
Adds timestampntz to the capabilities with an integration test. See [this notebook](https://e2-dogfood.staging.cloud.databricks.com/editor/notebooks/2154539344732364?o=6051921418418893#command/7952259781755525) for how the table was created.
=> Python connector TIMESTAMP_NTZ support

dev/python_release.sh
Resolved some `shellcheck` warning/errors, and made the script more portable.
cc: @PatrickJin-db
=> refactor: Resolve lint errors in python release script.

spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
TestDeltaSharingClient is missing the additional parameter `retrySleepInterval` from PR: https://github.com/delta-io/delta-sharing/pull/653
=> Fix RemoteDeltaLogSuite failure

python/delta_sharing/tests/test_delta_sharing.py
This test was failing when trying to convert the expected timestamp from `object` to `datetime64[us]` because pandas would internally convert it to `datetime64[ns]` first, which would lead to a timestamp out of bounds error. This PR fixes this issue.
=> Fix timestampntz test

client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
This table was added for python connector timestampntz support but the corresponding scala client test was not updated.
=> Update listAllTables test with timestampntz_cdf_table

PROTOCOL.md
Add examples in PROTOCOL for query with startingVersion, and fixed some table names used in examples and pre-signed urls.
=> Add examples in PROTOCOL for query with startingVersion

python/delta_sharing/_internal_auth.py, python/delta_sharing/delta_sharing.py, python/delta_sharing/protocol.py, python/delta_sharing/reader.py, python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_auth.py, python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_oauth_client.py, python/delta_sharing/tests/test_protocol.py, python/delta_sharing/tests/test_reader.py, python/delta_sharing/tests/test_rest_client.py, python/dev/.gitignore, python/dev/lint-python, python/dev/reformat
The command that checks if black is installed is incorrect. Fixing these scripts will almost completely eliminate time spent fixing lint issues. 
Also reformatted all of the python code using black. Actual code changes are all in `dev`
=> Fix Python lint and reformat scripts 

.github/workflows/build-and-test.yml, .github/workflows/build-kernel-wheels.yml
Ubuntu-20.04 is being deprecated in Github workflow. See https://github.com/actions/runner-images/issues/11101
=> Upgrade Github workflow to use higher ubuntu version

.github/workflows/build-kernel-wheels.yml
Add Ubuntu 22.04 to python wheel build workflow, as plenty of DBR versions are still using 22.04, e.g. https://docs.databricks.com/aws/en/release-notes/runtime/15.4lts#system-environment
=> Add Ubuntu 22.04 to python wheel build workflow

client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala
It is possible that refreshRes.expirationTimestamp is None. When it is None, None.get throws an exception and causing register to fail.
=> Fix logging when refreshRes.expirationTimestamp is None

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
Use e.getMessage in user facing error, to avoid it being over loaded by stacktrace.
=> branch-1.2: Use e.getMessage in user facing server error 

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
Use e.getMessage in user facing error, to avoid it being over loaded by stacktrace.
=> Use e.getMessage in user facing server error

client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, client/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala, client/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala, client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, client/src/main/scala/io/delta/sharing/spark/util/QueryUtils.scala, client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
This change updates the keying strategy of the existing pre-signed URL cache (which stores fileId -> fileUrl mappings) to account for different query shapes on the same table. Previously, the cache key only included the table path, so a new query with different parameters could overwrite existing cache entries. This update ensures correctness by incorporating the full query context into the cache key.
**Query Parameters by Query Type:**
**Snapshot Queries:**
- Filters
- Limit
- Table version
**Change Data Feed (CDF) Queries:**
- A Map[String, String] of CDF options, including:
- Starting version
- Ending version
Filters are excluded from the key, as files are fetched for the entire version range and filtered in memory. CDF queries also do not support limits.
**Streaming Queries:** …
=> Adding queryParamsHashId into tablePath for Snapshot/CDF/Streaming queries

client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala, client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala, spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
This change removes the timestamp suffix from the table path, as it causes the path to differ for every query. To enable cache sharing across multiple queries on the same table, we now use a query parameter hash ID instead.
=> Use query parameter hash ID instead of timestamp suffix for table path

client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingSourceOffset.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceOffsetSuite.scala
DBR 16.x uses an incompatible JSON version. This causes failures at execution time.  
Solution: Rewrite the code to remove dependency on JValue in the repo.
=> Don't use JValue in validateSourceVersion

server/src/main/scala/io/delta/sharing/server/model.scala
In the previous [PR](https://github.com/delta-io/delta-sharing/pull/711), the field for `errorMessage` was misnamed as `endStreamAction` in the server model. This is a fast follow to fix this change. This field is currently added in the server model to maintain consistency in the format of `EndStreamAction`, however it isn't actively used in any code path. See my comment from the original PR for more context:
> I have added the same field within the Server implementation. However due to the difference in [the way](https://github.com/delta-io/delta-sharing/blob/branch-1.2/server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala#L613) the server process streaming requests, we need to figure whether we want to implement this for the open source server and the best way to do …
=> Fix misnamed field in endStreamAction in server model

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/model.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, server/src/main/scala/io/delta/sharing/server/model.scala
Backporting changes for parsing errorMessage in endStreamAction in the client for branch-1.1.
Testing Branch 1.1 on DBR version 15.4 LTS :
Previous PR: https://github.com/delta-io/delta-sharing/pull/711
=> [Backport-1.1]: Parse Error Message in Client in EndStreamAction

server/src/main/scala/io/delta/sharing/server/model.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
Backporting EndStreamAction with client errorMessage for branch 0.7.
Testing on DBR 13.3 with this version of the client
=> [Backport-0.7]: Parse error message in client in EndStreamAction

server/src/main/scala/io/delta/sharing/server/model.scala
When making the branch cut for 1.3. The implementation [PR](https://github.com/delta-io/delta-sharing/pull/711) for endStreamAction with error message was already merged in. However, the [PR](https://github.com/delta-io/delta-sharing/pull/715) to fix the field was not merged in. This is a backport to fix that misnamed field.
To also confirm. I have tested branch-1.3 on DBR 17.x. Here is the result. The error message is showing but it is a little different. Want to make sure this is okay since it seems to wrapped by a runtime exception.
=> [Backport-1.3]: Fix misnamed field in server endStreamAction

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/model.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, server/src/main/scala/io/delta/sharing/server/model.scala
Add functionality to parse error endStreamAction within the open source client.
Add unit tests to ensure that error within EndStreamAction is properly parsed.
End to End Testing on 16.3 with branch 1.2
=> [Backport-1.2]: Parse Error Message in Client in EndStreamAction

client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, client/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala
In the previous `CacheTable` implementation, each query was registered as a separate cache entry, which inherently avoided race conditions. However, the new `QuerySpecificCachedTable` groups identical queries under the same cache entry. This change requires us to ensure thread safety during both registration and refresh operations.
Key details:
- A single background refresh thread is responsible for updating the cache.
- There can be multiple concurrent registration threads, each triggered by queries on the same table path.
- To ensure safe concurrent access, we must guard against race conditions between register and refresh logic.
`registerQuerySpecificCachedTable` uses `cache.compute(tablePath, (_, existingTable) -> ...)` to ensure atomic updates when multiple registration threads …
=> Handle race condition between a refresh thread and register threads

.github/workflows/build-and-test.yml, build.sbt, client/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala, client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala, client/src/main/scala/io/delta/sharing/spark/perf/DeltaSharingLimitPushDown.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemSuite.scala, client/src/test/scala/io/delta/sharing/client/util/ProxyServer.scala, client/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala, spark/src/test/scala/io/delta/sharing/spark/TestStorageProxyServer.scala
For client and spark build:
- Upgrade spark version to 4.0.0-preview1
- Upgrade scala version to 2.13.13
- Upgrade Java version to 17
Server build is still using spark 3 and java 8
=> Upgrade client/spark to use Spark 4.0.0-preview1

python/delta_sharing/delta_sharing.py, python/delta_sharing/reader.py, python/delta_sharing/tests/test_reader.py
This PR contains two optimizations:
1. When converting from arrow to pandas, read batches of rows at a time instead of entire parquet files. This change should eliminate pyarrow overhead almost entirely, which may be up to 40-50% reduction in memory usage.
2. Set `split_blocks=False`. I believe `split_blocks=True` was initially introduced in case it might help with memory usage during the arrow to pandas conversion. However, it should be set to false for three reasons:
-  In my testing, it doesn't affect the memory usage much (if at all).
-  We are converting small batches at a time now, so the memory usage of the conversion is negligible now (expect maybe if the table contains an extremely large number of columns)
-  As per the [documentation](https://arrow.apache.org/docs/python/generate …
=> Reduce memory usage in parquet format code path

client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, python/delta_sharing/delta_sharing.py, python/delta_sharing/reader.py, python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_reader.py, server/src/test/scala/io/delta/sharing/server/TestResource.scala
Reduces memory consumption when using delta-kernel-rs by converting each batch into a pandas dataframe and concatenating the results together, rather than creating a pyarrow table from all the batches and converting that table with all the results. The pyarrow table usually remains in memory during the conversion to pandas, so it is best to convert smaller batches to pandas rather than the entire table.
This change is gated behind the `convert_in_batches` param.
Tested with integration test.
Also added some unit tests for #737 involving parquet format batch convert + limit.
=> Reduce memory usage in delta format code paths

client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, dev/python_release.sh, python/delta_sharing/_internal_auth.py, python/delta_sharing/delta_sharing.py, python/delta_sharing/protocol.py, python/delta_sharing/reader.py, python/delta_sharing/rest_client.py, python/delta_sharing/tests/test_auth.py, python/delta_sharing/tests/test_delta_sharing.py, python/delta_sharing/tests/test_oauth_client.py, python/delta_sharing/tests/test_protocol.py, python/delta_sharing/tests/test_reader.py, python/delta_sharing/tests/test_rest_client.py, python/delta_sharing/version.py, python/dev/.gitignore, python/dev/lint-python, python/dev/reformat, server/src/test/scala/io/delta/sharing/server/TestResource.scala
Main changes are #737 and #723. #668 was backported too to avoid merge conflicts from formatting differences, and #660 was backported too so that I could use the release script without issues.
=> Release Python Connector 1.3.3

client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystem.scala, client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystemHttpClient.scala, client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystemHttpClientBuilder.scala, client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemHttpClientSuite.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemSuite.scala
The previous code touched too much Apache HttpClient internals resulting in certain edge cases not being considered when HTTPS downgrade and proxy settings are being used. This creates a delegating HttpClient that wraps a proxy and a non-proxy HttpClient so that we can minimize overriding internal methods of how HttpClient works. Adding anything more within these internals to fix this issue would make it more difficult to maintain and may introduce other bugs.
This also adds wildcard DNS support for no proxy hosts.
Fixes #747
=> Support HTTPS downgrade when not using the proxy. Add support for wildcard DNS support for no proxy hosts.

client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala, client/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala
This PR introduces a new `keepUrlsAfterRefsGone` boolean parameter to the `QuerySpecificCachedTable` class and related methods in `PreSignedUrlCache.scala`. This enhancement provides more flexible control over URL retention behavior when all FileIndex references are garbage collected. New queries don't need to be concurrent to reuse the existing urls.
=> Add keepUrlsAfterRefsGone parameter to QuerySpecificCachedTable for flexible URL retention

client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala
Cherry pick from master to branch-1.3 
- Add logging for file ID mismatches in QuerySpecificCachedTable registration (#760)
=> Add logging for file ID mismatches in QuerySpecificCachedTable registration (#760)

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala, client/src/main/scala/io/delta/sharing/client/model.scala, client/src/main/scala/io/delta/sharing/client/util/RetryUtils.scala, client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala, client/src/test/scala/io/delta/sharing/client/util/RetryUtilsSuite.scala, server/src/main/scala/io/delta/sharing/server/model.scala
Cherry-pick https://github.com/delta-io/delta-sharing/commit/b33530cc6d5baca39f9d14a074db393c62285c3e to branch-1.2
=> . (#771)[client] Add retry based on the httpStatusErrorCode in endStreamAction

server/src/main/scala/io/delta/sharing/server/model.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala, spark/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala, spark/src/main/scala/io/delta/sharing/spark/model.scala, spark/src/main/scala/io/delta/sharing/spark/util/RetryUtils.scala, spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala, spark/src/test/scala/io/delta/sharing/spark/util/RetryUtilsSuite.scala
Apply the changes from https://github.com/delta-io/delta-sharing/commit/b33530cc6d5baca39f9d14a074db393c62285c3e to branch-0.7
=> Add retry based on the httpStatusErrorCode in endStreamAction
