python/delta_sharing/rest_client.py

fix ListSharesResponse typo in rest_client.py

---

python/delta_sharing/rest_client.py
python/delta_sharing/tests/test_rest_client.py

Added a retry function for DataSharingRestClient.
Added unit tests.

Add retry with exponential backoff for Python client

---

PROTOCOL.md

Update PROTOCOL.md with note about the items field

Add note about missing items

---

README.md
build.sbt
dev/release.sh

- Add a release script to make the release process simpler.
- Update README to prepare the 0.2.0 release.

Add a release script and update README for 0.2.0 release

---

PROTOCOL.md
python/delta_sharing/protocol.py
python/delta_sharing/rest_client.py
python/delta_sharing/tests/test_profile.json
python/delta_sharing/tests/test_protocol.py
python/dev/reformat
spark/src/main/scala/io/delta/sharing/spark/DeltaExchangeProfileProvider.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingFileProfileProviderSuite.scala

Adds expirationTime as a field of DeltaSharingProfile to serve as an informational field indicating when the token is going to expire.

[SC-88052] Adds expirationTime as a field of DeltaSharingProfile

---

build.sbt

Change the location of `package.scala` file to follow https://docs.scala-lang.org/tour/package-objects.html

[MINOR] Change the version file location

---

server/src/test/scala/io/delta/sharing/server/config/ServerConfigSuite.scala
server/src/universal/conf/delta-sharing-server.yaml.template

This PR updates the server config template to include examples for Azure.

Update the server config template for Azure

---

PROTOCOL.md

Incremental changes from https://github.com/delta-io/delta-sharing/pull/85
Please review by viewing the markdown file directly.
https://github.com/delta-io/delta-sharing/blob/a701ef3b70af34a8e87ae6da93b71d6652f4e97d/PROTOCOL.md

Add Response code and errors in Protocol APIs

---

server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/main/scala/io/delta/sharing/server/SharedTableManager.scala
server/src/test/scala/io/delta/sharing/server/SharedTableManagerSuite.scala

Improve the error message for the /share/schema/table APIs

---

README.md

:wave: 
Just a μ-fix on the documentation.
thanks for this awesome tool :pray:

Use the latest version in readme.

---

server/src/main/protobuf/protocol.proto
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala

Accept tableVersion parameter for queryTable API

Accept tableVersion parameter for queryTable API

---

build.sbt
server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala

Upgrade dependency on delta-standalone to 0.4.0, so that new actions AddCDCFile and RemoveFile are available to support cdf query on OSS Delta Sharing Server
Closes #104

Upgrade dependency on delta-standalone to 0.4.0

---

server/src/main/scala/io/delta/standalone/internal/DeltaDataSource.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

Support readChangeFeed in DeltaSharingDataSource, with a new case class RemoteDeltaCDFRelation, DeltaSharingClient.getCDFFiles is not implemented yet.

[SC-99477] Support readChangeFeed in DeltaSharingDataSource

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/main/scala/io/delta/sharing/spark/model.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

Support versionOf in DeltaSharingClient.getFiles

Support versionOf in DeltaSharingClient.getFiles

---

python/delta_sharing/protocol.py
python/delta_sharing/rest_client.py
python/delta_sharing/tests/test_rest_client.py
server/src/main/scala/io/delta/standalone/internal/DeltaSharingCDCReader.scala

This PR has the following changes:
1) Implemented list_table_changes in the python rest client (made the method a POST on server side).
2) Added integ test.

Python rest client changes for CDF.

---

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/main/scala/org/apache/spark/sql/DeltaSharingScanUtils.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala

This PR has the following changes:
1) Hook up CDF relation to the file indices.
2) Integration tests.

spark connector changes to hook up CDF relation to the file indices.

---

python/delta_sharing/delta_sharing.py
python/delta_sharing/protocol.py
python/delta_sharing/reader.py
python/delta_sharing/rest_client.py
python/delta_sharing/tests/test_delta_sharing.py
python/delta_sharing/tests/test_protocol.py
python/delta_sharing/tests/test_reader.py
python/delta_sharing/tests/test_rest_client.py

Extends python connector:
- version for list_files_in_table
- configuration for Metadata

[SC-101703] Extends python connector with version for list_files_in_table and configuration for Metadata

---

server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala

Stops Handling of DeltaStandaloneException in DeltaSharingService

Stops Handling of DeltaStandaloneException in DeltaSharingService

---

python/delta_sharing/tests/test_delta_sharing.py
python/delta_sharing/tests/test_rest_client.py
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
server/src/test/scala/io/delta/sharing/server/TestResource.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala

Verify error message in client when log file or data file is missing

Verify error message in client when log file or data file is missing

---

README.md

In README, update version number from 0.4.0 to 0.5.0

In README, update version number from 0.4.0 to 0.5.0

---

README.md

Updated broken link to #delta-sharing-reference-server

Update README.md to fix broken link to #delta-sharing-reference-server

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala

Adds DeltaSharingOptions, to support DeltaSharingSource in the next PR.
Moves all options related logic from DeltaSharingDataSource to DeltaSharingOptions.

Adds DeltaSharingOptions

---

build.sbt
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingDataSource.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceCDFSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
version.sbt

Add StreamingQuery in the UserAgent http header for streaming queries

Add StreamingQuery in the UserAgent http header for streaming queries

---

python/delta_sharing/rest_client.py
python/delta_sharing/tests/test_rest_client.py
server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingRestClientSuite.scala
spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

This is to support delta sharing streaming on cdf, where timestamp is required as a column.

Return version and timestamp for each table for queryTable with version/timestamp

---

server/src/main/protobuf/protocol.proto
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala

Reverts get table api as it is unnecessary. Keeps the fix for integration tests and get table version changes.

Revert "Add get table api (#210)"

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala

Accept SC_NO_CONTENT as success status in DeltaSharingClient, for getTableVersion

Accept SC_NO_CONTENT as success status for getTableVersion in DeltaSharingClient

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala

Allow 0 for versionAsOf, to be consistent with Delta

Allow 0 for versionAsOf, to be consistent with Delta

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceCDFSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala

Apply partitionFilters to all file indexes

Apply partitionFilters to all file indexes

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingFileSystem.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingProfileProvider.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaCDFRelation.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingFileSystemSuite.scala
spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
spark/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala

Extends DeltaSharingProfileProvider to customize tablePath and refresher, for v 0.5.2

Extends DeltaSharingProfileProvider to customize tablePath and refresher

---

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala
spark/src/main/scala/io/delta/sharing/spark/model.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceCDFSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala

Support filtering on additional cdf columns: _commit_version/_commit_timestamp/_change_type

Support filtering on additional cdf columns

---

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/main/scala/io/delta/sharing/spark/model.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala

Support partition filters for cdf queries

Support partition filters for cdf queries in v0.5

---

spark/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala

Fix comparison of the expiration time with current timestamp for presigned urls

Fix comparison with the expiration time

---

README.md
RELEASE_NOTES.md
examples/README.md

README update on 0.6.2:
- Listed status of existing connectors
- Listed releases and notable features
- Added examples for CDF and streaming queries

README update on 0.6.2

---

spark/src/main/scala/io/delta/sharing/spark/filters/JsonPredicates.scala
spark/src/test/scala/io/delta/sharing/spark/filters/JsonPredicateSuite.scala

This is the first PR for Json based partition predicate filtering.
It implements basic operations and their evaluation.

Basic case classes for json filtering ops, and their evaluation.

---

spark/src/main/scala/io/delta/sharing/spark/filters/OpConverter.scala
spark/src/test/scala/io/delta/sharing/spark/filters/OpConverterSuite.scala

This PR implements utilities that convert Sql expression tree into json predicate op.

Op conversion from SQL to Json.

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

This PR changes the name of the new field form jsonPredicates to jsonPredicateHints as per offline discussion.

name change to jsonPredicateHints.

---

PROTOCOL.md

This PR documents the json predicates.

Document json predicates.

---

spark/src/main/scala/io/delta/sharing/spark/filters/OpConverter.scala
spark/src/test/scala/io/delta/sharing/spark/filters/OpConverterSuite.scala

This PR adds support for Sql IN predicate.
We limit the size of the list to guard against pathological inputs.

Add support for Sql IN predicate.

---

spark/src/test/scala/io/delta/sharing/spark/RemoteDeltaLogSuite.scala

This PR tests that the json predicate flag is honored by the client.

test json predicates with flag set to false.

---

server/src/main/protobuf/protocol.proto
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala
server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala
server/src/main/scala/io/delta/standalone/internal/JsonPredicateFilterUtils.scala
server/src/main/scala/io/delta/standalone/internal/JsonPredicates.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
server/src/test/scala/io/delta/sharing/server/TestDeltaSharingServer.scala
server/src/test/scala/io/delta/standalone/internal/JsonPredicateFilterUtilsSuite.scala
server/src/test/scala/io/delta/standalone/internal/JsonPredicateSuite.scala
server/src/universal/conf/delta-sharing-server.yaml.template

This PR implements the json predicate based filtering in the delta sharing server.
The changes are disabled by default.

delta sharing server changes for json predicates.

---

README.md

Updated to include lakehouse sharing by @rajagurunath

Update to include lakehouse-sharing

---

PROTOCOL.md
README.md

- Add the support for decimal in PROTOCOL
- Add the support for Google Spreadsheet connector in README
- Fix typo in README

A couple fixes to PROTOCOL and README page

---

spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaFileIndex.scala

In this PR, we enable the jsonPredicates in the spark connector.

Enable json predicates.

---

python/delta_sharing/__init__.py
python/delta_sharing/delta_sharing.py
python/delta_sharing/protocol.py
python/delta_sharing/tests/test_delta_sharing.py
python/delta_sharing/tests/test_rest_client.py

Support get_table_version/get_table_protocol/get_table_metadata as top api in python

Support get_table_version/get_table_protocol/get_table_metadata in python

---

spark/src/main/scala/io/delta/sharing/spark/util/RetryUtils.scala

Retry on java.net.SocketTimeoutException, and add logging for why not retry.

Retry on java.net.SocketTimeoutException

---

spark/src/main/scala/io/delta/sharing/spark/util/RetryUtils.scala

Fix the error order of client retry, and throw exception when not retrying.

Fix the error order of client retry

---

delta-sharing-protocl-api-description.yml

Copied OpenAPI document from [rivebank](https://github.com/delta-incubator/riverbank/blob/main/api-description.ymll)

feat: copied OpenAPI document from rivebank repo

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala

Add logInfo for maxVersionsPerRpc

Add logInfo for maxVersionsPerRpc

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala

Add logInfo for maxVersionsPerRpc in branch 0.7

Add logInfo for maxVersionsPerRpc in branch 0.7

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala
spark/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala

Initialize DeltaSharingRestClient in DeltaSharingRestClient.scala

Initialize DeltaSharingRestClient in DeltaSharingRestClient.scala

---

python/delta_sharing/version.py
version.sbt

Release 0.6.9

---

python/delta_sharing/version.py
version.sbt

Release 0.7.1

---

python/delta_sharing/version.py
version.sbt

Release 0.7.2

---

python/delta_sharing/version.py
version.sbt

Release 0.7.3

---

python/delta_sharing/version.py
version.sbt

Release 0.7.4

---

python/delta_sharing/version.py
version.sbt

Release 0.7.5

---

PROTOCOL.md
server/src/main/scala/io/delta/sharing/server/config/ServerConfig.scala
server/src/main/scala/io/delta/standalone/internal/ColumnRange.scala
server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala
server/src/main/scala/io/delta/standalone/internal/JsonPredicateEvaluatorV2.scala
server/src/main/scala/io/delta/standalone/internal/JsonPredicateFilterUtils.scala
server/src/main/scala/io/delta/standalone/internal/JsonPredicates.scala
server/src/main/scala/io/delta/standalone/internal/TimestampUtils.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
server/src/test/scala/io/delta/standalone/internal/ColumnRangeSuite.scala
server/src/test/scala/io/delta/standalone/internal/JsonPredicateEvaluatorV2Suite.scala
server/src/test/scala/io/delta/standalone/internal/JsonPredicateFilterUtilsSuite.scala
server/src/test/scala/io/delta/standalone/internal/JsonPredicateSuite.scala
server/src/test/scala/io/delta/standalone/internal/TimestampUtilsSuite.scala
server/src/universal/conf/delta-sharing-server.yaml.template

This PR has the following changes:
- Add support for json predicates in the OSS server.
- Unit tests and integration tests.

Support Json V2 predicates in OSS delta sharing server.

---

python/delta_sharing/reader.py
python/delta_sharing/rest_client.py
python/delta_sharing/tests/test_reader.py
python/delta_sharing/tests/test_rest_client.py
server/src/test/scala/io/delta/sharing/server/TestResource.scala

In this PR, we add support for json predicates in the python connector.
It also adds an integration test.

Support json predicates in python/pandas connector.

---

build.sbt

Update build.sbt in main to sync with branch-0.7

Update build.sbt in main to sync with branch-0.7

---

client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala
client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
client/src/main/scala/io/delta/sharing/spark/perf/DeltaSharingLimitPushDown.scala

Move limit pushdown config to ConfUtils in branch 1.0

Move limit pushdown config to ConfUtils in branch 1.0

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala

Fix type used for DeltaTableFiles

Fix type  of files used for DeltaTableFiles

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Fix type of files used for DeltaTableFiles

Fix type of files used for DeltaTableFiles

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Fix type of files used for DeltaTableFiles

Fix type of files used for DeltaTableFiles in branch 1.0

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/client/model.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

Allow different response format, will let the caller decide the behavior

Allow different response format

---

python/delta_sharing/rest_client.py

Update rest_client.py remove debug info

Update rest_client.py remove debug info

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystem.scala

Adds more logging in DeltaSharingFileSystem, to understand # of calls on pre-signed urls.
Same PR in branch-1.0 as https://github.com/delta-io/delta-sharing/pull/456

Adds more logging in DeltaSharingFileSystem in branch 1.0

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala

Handle ConnectionClosedException in place in DeltaSharingRestClient.getResponse in branch 0.7, so we can surface the invalid json string of the error to the user.

Handle ConnectionClosedException in place in branch-0.7

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala

Add queryID in userAgent for spark delta sharing queries

Add queryID in userAgent for spark delta sharing queries

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala

Add queryID in userAgent for spark delta sharing queries in branch 1.0

Add queryID in userAgent for spark delta sharing queries in branch 1.0

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/client/model.scala
client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientDeltaSuite.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
server/src/main/protobuf/protocol.proto
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/main/scala/io/delta/sharing/server/model.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

Add async api support in delta-sharing client

use async api in delta sharing client for view query

---

PROTOCOL.md
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala

Fix test and protocol description about delta sharing streaming rpc internal

Fix test and protocol description about delta sharing streaming rpc internal

---

server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala

Fetch next page should not have pending state.

Fix flakiness of async api on delta sharing server

---

client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientDeltaSuite.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
server/src/main/scala/io/delta/kernelsharedtable/DeltaSharedTableKernel.scala
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceCDFSuite.scala

getEndStreamAction added when refreshToken is True

getEndStreamAction added when refreshToken is True

---

client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
python/delta_sharing/tests/test_delta_sharing.py
server/src/main/scala/io/delta/common/SnapshotChecker.scala
server/src/main/scala/io/delta/kernelsharedtable/DeltaSharedTableKernel.scala
server/src/main/scala/io/delta/sharing/server/DeltaAction.scala
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
server/src/test/scala/io/delta/sharing/server/TestResource.scala

added column mapping functionality to server and wrote 2 corresponding tests

column mapping functionality added to server

---

server/src/main/scala/io/delta/sharing/kernel/internal/DeltaSharedTableKernel.scala
server/src/main/scala/io/delta/sharing/kernel/internal/JsonPredicatePruner.scala
server/src/main/scala/io/delta/sharing/kernel/internal/PredicateConverter.scala
server/src/main/scala/io/delta/sharing/server/DeltaSharedTableLoader.scala
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/main/scala/io/delta/sharing/server/common/JsonPredicates.scala
server/src/main/scala/io/delta/sharing/server/common/JsonUtils.scala
server/src/main/scala/io/delta/sharing/server/common/actions/DeltaAction.scala
server/src/main/scala/io/delta/standalone/internal/DeltaSharedTable.scala
server/src/main/scala/io/delta/standalone/internal/JsonPredicateFilterUtils.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
server/src/test/scala/io/delta/standalone/internal/JsonPredicateFilterUtilsSuite.scala
server/src/test/scala/io/delta/standalone/internal/JsonPredicateSuite.scala

renamed packages, moved jsonutils to common package, and removed not used variables

Refactor server code

---

python/delta_sharing/delta_sharing.py

Fix for issue outlined here: https://github.com/delta-io/delta-sharing/issues/526

nextPageToken empty string catch

---

.github/workflows/build-and-test.yml
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
python/delta-kernel-python/Cargo.toml
python/delta-kernel-python/src/lib.rs
python/delta_sharing/reader.py
python/delta_sharing/rest_client.py
python/delta_sharing/tests/test_delta_sharing.py
python/requirements-dev.txt
server/src/main/scala/io/delta/sharing/kernel/internal/DeltaSharedTableKernel.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
server/src/test/scala/io/delta/sharing/server/TestResource.scala

Support for DV and column mapping with column partition

Increase delta-kernel-rust version to 0.2

---

python/delta-kernel-rust-sharing-wrapper/Cargo.toml

change delta-kernel-rust-sharing-wrapper to 0.1.0

change delta-kernel-rust-sharing-wrapper to 0.1.0

---

.github/workflows/build-kernel-wheels.yml

Update Build Kernel Wheels To Run Only When Needed

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala
spark/src/main/scala/io/delta/sharing/spark/DeltaSharingProfileProvider.scala

* add custom http header provider
* remove unncessary import
* change it
* fix
* check headers

[BACKPORT] Add a Custom Http Header Provider (#192)

---

dev/spark_release.sh

To release delta-sharing-client/delta-sharing-spark only.

Add spark_release.sh

---

client/src/test/scala/io/delta/sharing/client/auth/OAuthClientSuite.scala

Sometimes in `OAuthClientSuite.scala`, after invoking server.shutdown(), the HTTP server does not fully stop, leading to the port not being released. This PR adds an additional safeguard to ensure the test server releases the port properly.

fixed a flaky test

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystem.scala
client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestStorageProxyServer.scala

cherry-pick commits from a[ pr against master](https://github.com/delta-io/delta-sharing/pull/559) for 1.2.0 onto 1.1  to be released as delta-sharing 1.1.2

cherry-pick http downgrade commits into 1.1

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala

Add more debugging info to DeltaSharingClient and DeltaSharingSource, especially about the queryId and tableid and table name.

Add more debugging info to DeltaSharingClient and DeltaSharingSource

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
server/src/main/scala/io/delta/sharing/kernel/internal/DeltaSharedTableKernel.scala
server/src/main/scala/io/delta/sharing/server/DeltaSharedTableProtocol.scala
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/main/scala/io/delta/standalone/internal/DeltaSharedTable.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala

Support includeEndStreamAction for cdf queries in both delta sharing server and client.
Also updated comments and logs.

Support includeEndStreamAction for cdf queries in both server and client 

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala

Improve logging and "Check Headers" test

Improve logging and "Check Headers" test

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/client/util/RetryUtils.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala
client/src/test/scala/io/delta/sharing/client/util/RetryUtilsSuite.scala

Add MissingEndStreamActionException and retry on it.

Retry on MissingEndStreamActionException

---

server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

Two nit fixes: variable name and test cleanup

Two nit fixes: variable name and test cleanup

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Some tiny fixes about logging in DeltaSharingClient

Some tiny fixes about logging in DeltaSharingClient

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala
client/src/test/scala/io/delta/sharing/client/util/ConfUtilsSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

Set default of includeEndStreamAction to false

Set default of includeEndStreamAction to false

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala
client/src/main/scala/io/delta/sharing/client/util/RetryUtils.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientDeltaSuite.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
client/src/test/scala/io/delta/sharing/client/util/ConfUtilsSuite.scala
client/src/test/scala/io/delta/sharing/client/util/RetryUtilsSuite.scala
server/src/main/scala/io/delta/sharing/server/DeltaSharingService.scala
server/src/main/scala/io/delta/standalone/internal/DeltaSharedTableLoader.scala
server/src/test/scala/io/delta/sharing/server/DeltaSharingServiceSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSourceSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala

- Backport includeEndStreamAction in DeltasharingService to branch-1.0
- Backport logging changes to branch-1.0

Backport includeEndStreamAction in DeltasharingService to branch-1.0

---

client/src/main/scala/io/delta/sharing/spark/perf/DeltaSharingLimitPushDown.scala

DeltaSharingLimitPushDown uses the pattern with LogicalRelation which could change, in terms of parameter in constructor. Spark community made a change in upcoming Spark 4.0 (https://github.com/apache/spark/pull/48676) to add a new parameter in LogicalRelation, and the change will break the pattern.
Since the pattern only picks up the relation from LogicalRelation, the pattern object Spark community introduced along with the above change (https://github.com/apache/spark/pull/48605) would be helpful to not encounter the issue in upcoming Spark 4.0 when Delta Sharing supports the version.

Introduce pattern object for LogicalRelation to avoid coupling with all params

---

python/delta_sharing/version.py

Previous PR (#613) accidentally changed version.py to 0.0.5 for uploading to testPyPI. This changes it back.

Small version fix

---

README.md

Add example of using jsonPredicateHints for load_as_pandas in README

Add example of using jsonPredicateHints for load_as_pandas in README

---

.github/workflows/build-and-test.yml
README.md
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
python/README.md
python/delta-kernel-rust-sharing-wrapper/Cargo.toml
python/delta_sharing/delta_sharing.py
python/delta_sharing/protocol.py
python/delta_sharing/reader.py
python/delta_sharing/rest_client.py
python/delta_sharing/tests/test_delta_sharing.py
python/delta_sharing/tests/test_protocol.py
python/delta_sharing/tests/test_reader.py
python/delta_sharing/tests/test_rest_client.py
server/src/test/scala/io/delta/sharing/server/TestResource.scala

Cherry-picked python changes from main

Update python branch 1.3

---

client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala

The constructor for `ExpresssionEncoder` has changed in Spark 4.0 in https://github.com/apache/spark/commit/14de06e19d38b038e17dd94d43e2cdc767d588e5. This PR uses reflection to construct a copy of the AddFileEncoder so it'll be compatible across Spark versions.
Verified the fix in DBR using staging releases.

Use reflection to address parameter change in ExpressionEncoder in Spark 4.0

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Add table name in logging and add missing logging for streaming queries

Improve logging in DeltaSharingClient

---

PROTOCOL.md

Add in specification for share name to PROTOCOL.md

Update PROTOCOL.md with share name rules

---

PROTOCOL.md

Update PROTOCOL.md to correctly state that response is Delta

Update PROTOCOL.md to correctly state that response is Delta

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala

Cherry pick from master to branch-1.2 https://github.com/delta-io/delta-sharing/pull/681

Cherry pick from master to branch-1.2: Adding more logging in Spark client to help debugging

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala

Cherry pick from master to branch-1.1 https://github.com/delta-io/delta-sharing/pull/681

Cherry pick from master to branch-1.1: Adding more logging in Spark client to help debugging

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Fix error message in checkEndStreamAction

Fix error message in checkEndStreamAction

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Try to improve error message for server error, currently it's always the error below, which is not meaningful for debugging: 
```
Request to delta sharing server failed due to org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected.
```

Try to improve error message for server error

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Fix error message in checkEndStreamAction

Backport to branch 1.2: Fix error message in checkEndStreamAction 

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Fix error message in checkEndStreamAction

Backport to branch 1.1: Fix error message in checkEndStreamAction 

---

.github/workflows/build-and-test.yml

Upgrade Github workflow to use higher ubuntu version in branch 1.1

Upgrade Github workflow to use higher ubuntu version in branch 1.1

---

.github/workflows/build-and-test.yml

Upgrade Github workflow to use higher ubuntu version in branch 0.7

Upgrade Github workflow to use higher ubuntu version in branch 0.7

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala

1. Handle empty lines
2. Handle json parsing error on last line
3. Handle non-EndStreamAction on last line.

Add more checks and unit tests for checkEndStreamAction

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

The original goal of the PR is to backport https://github.com/delta-io/delta-sharing/pull/687, but it turns out that the cherry-pick cannot auto resolve as there are some previous changes in DeltaSharingClient not backported to branch-1.2. 
I want to include all them as there's no logical change and mostly about logging changes, it's good to keep the code in consistency for logging and debugging purpose.

Backport to branch-1.2: Try to improve error message for server error 

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala

Try to improve error message for server error, currently it's always the error below, which is not meaningful for debugging: 
```
Request to delta sharing server failed due to org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected.
```

Backport to branch-1.1: Try to improve error message for server error

---

spark/src/main/scala/io/delta/sharing/spark/DeltaSharingClient.scala

Try to improve error message for server error, currently it's always the error below, which is not meaningful for debugging: 
```
Request to delta sharing server failed due to org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected.
```

Backport to branch-0.7: Try to improve error message for server error

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala

* Add more checks and unit tests for checkEndStreamAction
* fix variable name

Add more checks and unit tests for checkEndStreamAction (#693)

---

version.sbt

Set version to 0.7.11-SNAPSHOT

Set version to 0.7.11-SNAPSHOT

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingProfileProvider.scala
client/src/main/scala/org/apache/spark/delta/sharing/PreSignedUrlCache.scala
client/src/test/scala/org/apache/spark/delta/sharing/CachedTableManagerSuite.scala

Cherry pick PR from master to branch-1.3
- https://github.com/delta-io/delta-sharing/pull/708
- https://github.com/delta-io/delta-sharing/pull/719

Cherry pick pre-signed url cache PRs into branch-1.3

---

.github/workflows/build-and-test.yml
build.sbt
client/src/main/scala/io/delta/sharing/spark/DeltaSharingOptions.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingSource.scala
client/src/main/scala/io/delta/sharing/spark/RemoteDeltaLog.scala
client/src/main/scala/io/delta/sharing/spark/perf/DeltaSharingLimitPushDown.scala
client/src/main/scala/org/apache/spark/sql/DeltaSharingScanUtils.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemSuite.scala
client/src/test/scala/io/delta/sharing/client/util/ProxyServer.scala
client/src/test/scala/io/delta/sharing/spark/DeltaSharingOptionsSuite.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala
spark/src/test/scala/io/delta/sharing/spark/TestDeltaSharingClient.scala
spark/src/test/scala/io/delta/sharing/spark/TestStorageProxyServer.scala

cherry pick PR from branch-1.3 to main:
- https://github.com/delta-io/delta-sharing/pull/728
- https://github.com/delta-io/delta-sharing/pull/729

Cherry-pick spark 4.0.0 upgrade to main branch

---

build.sbt

https://github.com/apache/spark/releases/tag/v4.0.0

Switch to spark 4.0.0 official release

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystem.scala
client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystemHttpClient.scala
client/src/main/scala/io/delta/sharing/client/DeltaSharingFileSystemHttpClientBuilder.scala
client/src/main/scala/io/delta/sharing/client/util/ConfUtils.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemHttpClientSuite.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingFileSystemSuite.scala

Support HTTPS downgrade when not using the proxy. Add support for wildcard DNS support for no proxy hosts.

---

spark/src/test/scala/io/delta/sharing/spark/DeltaSharingIntegrationTest.scala
spark/src/test/scala/io/delta/sharing/spark/DeltaSharingSuite.scala

use integrationTest instead of test

Fix flaky test "spark read limit"

---

build.sbt
dev/spark_release.sh
project/plugins.sbt

[Backport 1.0] Switch OSSHR service to Central Publishing Portal (#763)

[Backport 1.0] Switch OSSHR service to Central Publishing Portal (#763)

---

build.sbt
dev/spark_release.sh
project/plugins.sbt

[Backport 1.1]Switch OSSHR service to Central Publishing Portal (#763)

[Backport 1.1]Switch OSSHR service to Central Publishing Portal (#763)

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/client/model.scala
client/src/main/scala/io/delta/sharing/client/util/RetryUtils.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
client/src/test/scala/io/delta/sharing/client/util/RetryUtilsSuite.scala
server/src/main/scala/io/delta/sharing/server/model.scala

Cherry-pick https://github.com/delta-io/delta-sharing/commit/b33530cc6d5baca39f9d14a074db393c62285c3e to branch-1.3

[client] Add retry based on the httpStatusErrorCode in endStream 

---

client/src/main/scala/io/delta/sharing/client/DeltaSharingClient.scala
client/src/main/scala/io/delta/sharing/client/model.scala
client/src/main/scala/io/delta/sharing/client/util/RetryUtils.scala
client/src/main/scala/io/delta/sharing/spark/DeltaSharingErrors.scala
client/src/test/scala/io/delta/sharing/client/DeltaSharingRestClientSuite.scala
client/src/test/scala/io/delta/sharing/client/util/RetryUtilsSuite.scala
server/src/main/scala/io/delta/sharing/server/model.scala

Cherry-pick https://github.com/delta-io/delta-sharing/commit/b33530cc6d5baca39f9d14a074db393c62285c3e to branch-1.1

. (#771)[client] Add retry based on the httpStatusErrorCode in endStreamAction
